### ISSUE TITLE
Huelloween app hue motion sensor support?

### ISSUE THREAD

**Issue by kenhuang** [bwssytems/ha-bridge#1008]
Love this project since version 0.x

Recently try to setup halloween theme around the house, downloaded the app huelloween from App Store, tested great with ha-bridge with my own milight nodejs api. Next steps I would like to do is trigger the theme via motion sensor.

The app did support for hue’s motion sensor, is there a way I can link a motion sensor to ha-bridge, so that it can work within the app? I have xiaomi motion sensor and WeMo motion sensor.

Thanks for your help in advance!

**Comment by bwssytems** [comment]
The ha-0bridge does not support the Hue motion sensor at this time.

**Comment by BernieHD** [comment]
Hi @bwssytems 
First, many many thanks for maintaining and supporting this great project!
I use HA-bridge to easily extend and customize my Magenta Smart Home (MSH) with ha-bridge running on a RPI Zero!
What would be the criteria to support Hue-motion sensors as devices with HA Bridge or in other words an additional device type emulating a Hue motion detector? That would greatly enhance potential use cases for HA-Bridge because it would open up HA Bridge from being a receiver of commands to a sender of commands.
Your feedback is highly welcome!
Best regards
Bernhard

**Comment by BernieHD** [comment]
Hi @bwssytems
First, many many thanks for maintaining and supporting this great project!
I use HA-bridge to easily extend and customize my Magenta Smart Home (MSH) with ha-bridge running on a RPI Zero!
What would be the criteria to support Hue-motion sensors as devices with HA Bridge or in other words an additional device type emulating a Hue motion detector? That would greatly enhance potential use cases for HA-Bridge because it would open up HA Bridge from being a receiver of commands to a sender of commands.
Your feedback is highly welcome!
Best regards
Bernhard
