### ISSUE TITLE
Alexa Duplication and recalling forgotten devices

### ISSUE THREAD

**Issue by petersmike** [bwssytems/ha-bridge#1027]
Has anybody had a situation like mine.  I have ha-bridge running on a raspberry pi 3+.  The ha-bridge interface to the X10 modules (via Mochad) works great from the ha-bridge web interface.  
The problem arises when I attempt to discover - I start with the Alexa Smart Homes where I forget all devices.  I refresh the Alexa page to confirm there are no devices identified.
Then I conduct a Discover - not only do I get duplicates, but it also "recalls" previously discovered devices.  
In my ha-bridge device.db file is only 4 devices.  While Alexa only finds 3 of the 4 devices, it seems to have a historical memory to recall devices that I have since removed.  (I did this because Alexa starting getting very confused with 15 devices - and started duplicating) .
All discovered devices are being called "Royal Philips Electronics smart device".

Environment: 1 Echo Dot Gen 3, two Echos Gen 2s.  Raspberry Pi3+ connected to X10 CM-15A for power line control.  

Do anybody have any suggestions as to why it duplicates and also why historical devices are recalled?

Thanks,
[Ha-bridge Log 181209.xlsx](https://github.com/bwssytems/ha-bridge/files/2661321/Ha-bridge.Log.181209.xlsx)
[Ha-bridge Log 181209.xlsx](https://github.com/bwssytems/ha-bridge/files/2661322/Ha-bridge.Log.181209.xlsx)

**Comment by audiofreak9** [comment]
You don't by any chance have two instances of the HA-Bridge running?  I've had two running by mistake, one at startup and one by command line - forgot to kill the command line one, got duplicate devices for a bit.

**Comment by petersmike** [comment]
Good Idea, but not in this case.  I did find some more information - it appears that the Alexa app launched by ha-bridge does not successfully forget.  Thus when I did a discover, it recalled previous devices.  
I found this after I though I had forgotten all devices, then ran the Alexa Mobile App on my tablet and noticed that the devices I though had been deleted were not.  
After clearing them with the mobile app, I re-discovered from the ha-bridge launched Echo app and it worked.  I have all the devices listed one time and the voice commands to Alexa correctly turn on and off the devices.

**Comment by bwssytems** [comment]
That is an interesting observation abotu the mobile app. I always used the browser interface to do a forget.

**Comment by sanderlv** [comment]
Oh... since having habridge running on a dedicated virttual ubuntu server I have this duplicate device issue. Before, with running it on docker I had for over a year no problems. I have tried everything. Deleting all devices one-by-one. Via the mobile app, via the alexa webpage, but no luck. I have 26 devices in habridge and keep getting 52 devices in alexa. The first 2 or 3 days running this on a dedicated server I seems to not have noticed this, It might have been there...?

**Comment by 3rdStng** [comment]
Still possibly appears to be an issue with duplicate devices. At least for me. I have one HA bridge running in a docker and am getting two of every device within my Echo listing. One that is labeled Dimmable Light and one that is labeled Royal Philips Electronics smart device. Did the code change on the back end that is causing these duplicates? Which one should I be using? 

![2019-07-28_114348](https://user-images.githubusercontent.com/24888063/62011492-d4012400-b12d-11e9-9c74-89e556cec9be.jpg)

**Comment by audiofreak9** [comment]
I have the exact same thing, every HA-Bridge device is discovered twice, one as Dimmable Light, one as Royal Philips Electronics smart device.  Currently on 5.3.0 RC13 and noticed since 5.21 or so as well.  I have a mix of Echo devices: Gen 1 Echo, Gen 1 Show, multiple Gen 1 & 2 dots, Gen 1 Spot.

**Comment by 3rdStng** [comment]
Never thought about the version of Echo's being the problem. I have:
- 1 Gen 1 Echo
- 1 Gen 1 Dot
- 1 Gen 3 Dot
- 3 Gen 2 Dots
(And one Wanna be Dot Eufy that is not plugged in.)

If I remove both lights and rediscover, the Dimmable light is only found. If I rediscover a second time, then the Royla Philips light is also found. Sometime, not all the time, this interferes with voice commands. Either "Provider is having issues" or "<Named> device is not responding...". If the device is not responding message is said, the light will still turn on or off.

**Comment by bwssytems** [comment]
This has been moved to the Community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-has-anybody-had-a-situation-like-mine-i-have-ha-bridge-running-on-a-raspberry-pi-3-the-ha-bridge-interface-to-the-x10-modules-via-mochad-works-great-from-the-ha-bridge-web-interfacethe-problem-arises-when-i-attempt-to-discover--i-start-with-the-alexa-smart-homes-where-i-forget-all-devices-i-refresh-the-alexa-page-to-confirm-there-are-no-devices-identifiedthen-i-conduct-a-discover--not-only-do-i-get-duplicates-but-it-also-recalls-previously-discovered-devicesin-my-ha-bridge-devicedb-file-is-only-4-devices-while-alexa-only-finds-3-of-the-4-devices-it-seems-to-have-a-historical-memory-to-recall-devices-that-i-have-since-removed-i-did-this-because-alexa-starting-getting-very-confused-with-15-devices--and-started-duplicating-all-discovered-devices-are-being-called-royal-philips-electronics-smart-device
