### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#1033]
Currently the Backup and restore of HA-Bridge works great.
However this saves the files to the device HA-Bridge is running on.
 If this device fails or if in a Pi and the SD card gets corrupt there is no way to retrieve a back up to restore.
Or am I missing the obvious?
It would be great if when trying to do a back up or restore HA-Bridge asked the location to save or restore from/to

**Comment by Hollybrook** [comment]
+1 on this issue.  I tried to stop HA-Bridge and ftp the config file, but it is locked for access.

**Comment by Hollybrook** [comment]
Sorry, I should have been more precise.  I was using sftp on my other machine but could not access the config file because it was "open for read" even after stopping the bridge on the Pi.

And to Tuicemen's point, a one button backup to other machine like HomeGenie provides would be an optimum solution.

**Comment by craigski** [comment]
I think the issue is the *.cfgbk backup files are owned by 'root'. The 'pi' user does not have read access when using ftp/scp from another machine:

pi@pi2:~/ha-bridge/data $ ls -lrt
total 24
-rw------- 1 root root 1430 Dec  7 09:05 habridge.config-2018-12-07-09-23-09.cfgbk
-rw-r--r-- 1 root root 3632 Dec  7 10:08 device.db-2018-12-07-14-52-05.bk
-rw------- 1 root root 1430 Dec  7 12:18 habridge.config-2018-12-07-14-51-57.cfgbk
-rw------- 1 root root 1780 Dec 14 21:52 habridge.config
-rw-r--r-- 1 root root 5710 Dec 15 14:21 device.db

Changing permissions of *.cfgbk to 644 same as the *.db and *.bk files would allow ftp/scp.

**Comment by tuicemen** [comment]
@craigski  you are correct changing the file permission will allow you to copy the cfgbk file.
Still a lot of extra work, if this could be avoided that would be awesome.

**Comment by bwssytems** [comment]
I have download working, next is upload

**Comment by tuicemen** [comment]
Awesome!!
