### ISSUE TITLE
X10 devices into a scene or automation on Smartthings

### ISSUE THREAD

**Issue by xerexa** [bwssytems/ha-bridge#1043]
When putting multiple X10 devices into a scene or automation on Smartthings, not all of the devices respond when the scene or automation is executed.
I believe it may be because commands are too rapid for the devices to respond.
I have looked for a fix for this but couldn't find one.

I would sincerely appreciate any help or advice.

**Comment by audiofreak9** [comment]
@xerexa If you are using HEYU to execute your X10 commands you can use a SCENE and execute it with HA-Bridge rather than multiple devices from the HA-Bridge.  You can add/edit your SCENE in the x10.conf file.  To find this file type: `$ heyu info`  You should see something like this:
```
Heyu version 2.11-rc2
Configuration at /etc/heyu/x10.conf
Powerline interface on /dev/ttyUSB0
Firmware revision Level = 1
Interface battery usage = 0:01  (hh:mm)
Raw interface clock: Tue, Day 365, 09:11:36
(--> Civil Time: Tue 01 Jan 2019   09:11:36 EST)
Uploaded schedule will expire in 1 days.
Housecode = M
0 = off, 1 = on,               unit  16.......8...4..1
Last addressed device =       0x1000 (1000000000000000)
Status of monitored devices = 0x0000 (0000000000000000)
Status of dimmed devices =    0x0000 (0000000000000000)
```
The second line is where your config file is located.  To edit the config file type:  `$ sudo nano /etc/heyu/x10.conf` Here is the SCENE info from HEYU 
```
# Scenes and Usersyns (User-defined synonyms):
# Format:  SCENE   Label Command1 <args> [; Command2 <args> [; ...
# Format:  USERSYN Label Command1 <args> [; Command2 <args> [; ...
# The label is limited to 32 characters and is case-sensitive.
# Scenes and Usersyns are both semicolon-separated lists of
# commands with their arguments which can be executed or used
# in macros as if their labels were ordinary Heyu commands.
# See 'man x10config' for the features and limitations of Scenes
# and Usersyns.
# (In the current version of heyu, the ONLY distinction between
# scenes and usersyns is the 'show' menus in which they appear.)
# Some examples:

# SCENE  blinker  on A1; off A1; on A1; off A1
# USERSYN normal_lights  on front_porch; on back_porch
# SCENE   tv_on   on tv_set; dimb living_room 10
```
Here is the SCENE that I use for my holiday lights:
```
SCENE   holiday_on  fon M1; pause 1.5; on M14,15; pause 1.5; dimb M5-10 5
SCENE   holiday_off  foff M1; pause 1.5; off M5-8; pause 1.5; off M9,10,14,15
```
I added the pause for 1.5 seconds to allow each set of commands to be executed.  I then created a device in HA-Bridge named "holiday". The On Items: `heyu holiday_on` and the Off Items: `heyu holiday_off`. I hope this helps, let me know if you have more questions.

**Comment by audiofreak9** [comment]
@xerexa 
Any luck with this suggestion?

**Comment by xerexa** [comment]
No luck so far.  I am running HA-Bridge on a dedicated Windows 10 machine with a Samsung Smartthings Hub (no HEYU). 
I have some ideas for a workaround but haven't had the time to try them yet.

**Comment by audiofreak9** [comment]
You can create one device in the HA-Bridge with all the devices you want to control and add delay between each call.

**Comment by audiofreak9** [comment]
@xerexa 
In your "On Items" add the first device you want to turn on in the Target Item (of course), but then in the Delay box add the delay in number of milliseconds.  Half a second would be a value of 500 would give a half second delay, etc.  Then add another device below the first, repeat the delay as needed, but don't forget to click add.  Repeat as many times as necessary.
