### ISSUE TITLE
Alexa app, error "Device doesn't support requested value"

### ISSUE THREAD

**Issue by chmasi** [bwssytems/ha-bridge#1044]
After upgrading to latest stable Version i got this error, and devices can not be switched anymore by Amazon Echo Device. Same issue with latest release Candidate.
Went back to Version 4.5.6 and everything is working again as expected.

**Comment by bwssytems** [comment]
Will take a look as I saw this the other day on my system.

**Comment by ammawel** [comment]
First of all thanks for the constant work on ha-bridge!
Unfortunately this error message is still present in the last release v5.3.0RC3 when devices are turned off. However, the devices are switched despite the message.
Greetings
Achim

**Comment by bwssytems** [comment]
Setting brightness return in state to be no less than 1

**Comment by SchmuFoo** [comment]
> ting brightness return in state to be no less than 1

Where do I set this? Somewhere in "http://192.168.178.38:8080/#!/editdevice" ?

**Comment by SchmuFoo** [comment]
> > ting brightness return in state to be no less than 1
> 
> Where do I set this? Somewhere in "http://192.168.178.38:8080/#!/editdevice" ?

@bwssytems I was wondering if you could give us an hint for that ;)?

**Comment by ballle98** [comment]
I think what is suggested is to edit the device and add a dim URL/cmd.  For me I added the following command "/usr/bin/logger ${device.name} dim ${intensity.percent}".  Then from bridge devices you can use the "test dim" button to set the brightness.  Make sure your device has state enabled (No state = false).  Also make sure to "Off State Resets Bri"=false and "On when Dim is present"=false.

The root cause seems to be brightness of 0 creates an error condition.

Not sure that dim state is persistent across reboot so may need a use curl to set all the brightness states  to 1 see https://github.com/bwssytems/ha-bridge#update-bridge-internal-light-state

**Comment by ballle98** [comment]
looks like not all values of "bri" are accepted.  I opened 2 terminals into my pi.  one running 
`watch curl http://127.0.0.1/api/username/lights/1`
and the other I would set different brightness values with
`curl -X PUT -d '{"bri": 253}' http://127.0.0.1/api/username/lights/1/bridgeupdatestate`

I originally used the value of 254 for 100% brightness but I saw the value get clobbered and set back to 0 when I turned the light on and off.  I tested the values 253 and 26 and they seem to work.

I could not get multiple startup actions to work so I created a new device called startup that calls a script that sets the brightness on all devices and set the startup action to on for this device.

`for i in {1..11}; do curl -X PUT -d '{"bri": 253}' http://127.0.0.1/api/username/lights/$i/bridgeupdatestate; echo; done`
