### ISSUE TITLE
Voice command colour change

### ISSUE THREAD

**Issue by poudenes** [bwssytems/ha-bridge#1060]
Hi,

I saw this question and the answer:

**Q: Can voice commands other than: ON, OFF and DIM/BRIGHT be used?**
_A: NO, the ha-bridge emulates a Philips HUE bridge. The interactions between a Philips HUE and and Amazon Echo are determined by Philips and Amazon. They are not changeable by the ha-bridge, so only: ON, OFF and DIM/BRIGHT verbal commands are available._

Im using Domoticz with Homebridge. Homebridge have a option to connect it with Alexa.
When devices discovered (output from Homebridge) you can turn bulbs on/off/dim and colour change.

Here the site of how this works:
https://www.npmjs.com/package/homebridge-alexa

So my question: Would it be possible to let it work ? To change colour as well within HA Bridge using Alexa in future... :)

**Comment by bwssytems** [comment]
Unfortunately, this is a problem with Alexa software and not the ha-bridge

**Comment by StephaneM60** [comment]
I'm not sure I understand how this is not HA-Bridge issue. I have some MiLight bulb set up in domoticz and I can change the light color just fine in domoticz. I then use HA Bridge to create color bulb devices and they show up as such in Alexa after discovery.

If I ask alexa to change the color on the bulb, it does send a request to HA Bridge, but the color doesn't change and from what I understand it's only because the color is send in H + L and there is nothing in the HA Bridge code to convert this value into RGB (well into the value that can be then transmitted to domoticz). I have not looked very hard but it seems to me that there is a code path in HA Bridge that is missing to correctly convert the HSL color.

So I don't see why it could not work (Note : I have done this test with an Echo Dot 2nd Gen triggering a routine created in the Alexa App, so both the routine and a requested color by voice on the Echo does produce a color request that is reaching HA Bridge).

**Comment by bwssytems** [comment]
@StephaneM60 Please turn on Debug for the HueMulator and send post the log. We'll see what is happening on the request end then.

**Comment by StephaneM60** [comment]
Sure, this is what happens when I request the light to be Red (directly from the Alexa application on an Android device)

03-08-2019 16:18:02.343 | DEBUG | HueMulator PUT called on api/* with request <<</api/e7d41ec59a844a4286fe35a4ed405a49/lights/14/state>>>, and body <<<{"hue":0,"sat":254}>>> | com.bwssystems.HABridge.hue.HueMulator
-- | -- | -- | --
03-08-2019 16:18:02.343 | DEBUG | hue state change requested: e7d41ec59a844a4286fe35a4ed405a49 from 192.168.70.175 body: {"hue":0,"sat":254} | com.bwssystems.HABridge.hue.HueMulator


Let me know if you need more (in the code, if 

03-08-2019 16:18:02.343 | DEBUG | HueMulator PUT called on api/* with request <<</api/e7d41ec59a844a4286fe35a4ed405a49/lights/14/state>>>, and body <<<{"hue":0,"sat":254}>>> | com.bwssystems.HABridge.hue.HueMulator
-- | -- | -- | --
03-08-2019 16:18:02.343 | DEBUG | hue state change requested: e7d41ec59a844a4286fe35a4ed405a49 from 192.168.70.175 body: {"hue":0,"sat":254} | com.bwssystems.HABridge.hue.HueMulator

Let me know if you need more informations (in the code, when I looked why it was not working, I remember that it is in the UpdateState or something like that that there is something missing, there is a test for the "hue" string, so it is somehow expected but after it is not used (only rgb is handled if I remembre correctly)

**Comment by bwssytems** [comment]
Well, Alexa is not giving red based on the body '''{"hue":0,"sat":254}'''

**Comment by StephaneM60** [comment]
Some more color values,l tested in the Alexa app :

Green : {"hue":21845,"sat":254}

Blue : {"hue":43690,"sat":254}

Yellow : {"hue":10923,"sat":254}

Red : {"hue":0,"sat":254}

Magenta : {"hue":54613,"sat":254}

Cyan : {"hue":32768,"sat":254}

Orange : {"hue":7100,"sat":254}

**Comment by bwssytems** [comment]
I have been updating the color handling which should now work with HSL which was broken.
