### ISSUE TITLE
Can't switch on from Harmony

### ISSUE THREAD

**Issue by PLCHome** [bwssytems/ha-bridge#1082]
The Harmony is sending color, bright and on state.
The habridge says that there is no color and no bright. 
But the on state will not be processed

The color and brightness are not parameterized

Version: 5.2.2. rc4

```
04-28-2019 17:08:15.108 | INFO | Dim url not available for state change, lightId: 3, userId: b24aed0f532c4752a14931e7ca1d9b80, from IP: 192.168.2.70, body: {"xy":[0,0],"on":true,"bri":252} | com.bwssystems.HABridge.hue.HueMulator
04-28-2019 17:08:15.109 | INFO | Color url not available for state change, lightId: 3, userId: b24aed0f532c4752a14931e7ca1d9b80, from IP: 192.168.2.70, body: {"xy":[0,0],"on":true,"bri":252} | com.bwssystems.HABridge.hue.HueMulator
```

**Comment by bwssytems** [comment]
There are 2 settings in the device when you edit a shown below:


On when Dim is present (Always uses on with a dim request otherwise it will ignore a given on was well. This is overidden by onFirstDim.) | false
-- | --
On with First Dim (If the device is not on in the ha-bridge state, it will send on instead of the dim.) | false


The setting "On when Dim is present" needs to be selected for this to work for the harmony.
