### ISSUE TITLE
Harmony Generate Bridge Device & Build a Button (not working)

### ISSUE THREAD

**Issue by Deojuvente** [bwssytems/ha-bridge#118]
i have downloaded the new version 2.0.7 from http://bwssystems.com but i cant use the button to generate. i read it was fixed :( but not working for me.. http://prntscr.com/b6sgnz & http://prntscr.com/b6sguz

**Comment by bwssytems** [comment]
I just tested this and it is working as expected. Can you elaborate on more on the issue?

**Comment by Deojuvente** [comment]
Hello BWS

i just emailed you whit some info i don't like to get public 
i hope this helps you

**Comment by bwssytems** [comment]
Just a thought here, when you click the generate or build button, all it does is create the entry in the add bridge device box below the list. You have to click the "Add Bridge Device" button for it to be added. This is because you should look at the name and you may want to modify it.

User has tried this and it is the solution

**Comment by Deojuvente** [comment]
thnx for your help and time
