### ISSUE TITLE
IP Address 0.0.0.0 Error

### ISSUE THREAD

**Issue by wyseguy79** [bwssytems/ha-bridge#128]
When I try and run the jar file with and without the config file my IP address displays "Listening on 0.0.0.0:XXXX". I can change the port number with no problem, but not matter what IP address I use that is associated with the NIC card it shows 0.0.0.0 and then "ignite failed... Address is already in use: bind" I also tried various ports and no luck.

I am running this on Windows Server 2012 R2 and have server IP address on this machine. Is there anything additional I have to do in order to get this running. Thanks for any assistance.

**Comment by bwssytems** [comment]
So, 0.0.0.0 is just the address to tell the OS to use all interfaces, the real issue is the port number, XXXX, is being utilized by another application on your machine OR a previous instance of the ha-bridge is running and not shutdown. You will need to override that on the command line as specified in the Readme on the main github page for the bridge.

**Comment by wyseguy79** [comment]
Thanks, I did try the command line port option as well. I will restart the machine tonight and try it fresh on various ports till something works!

**Comment by bwssytems** [comment]
Closing as this is answered
