### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by tinker3433** [bwssytems/ha-bridge#167]
HI,
In the instructions for Postv3.1fixes the instructions are still referring to: 
"wget https://github.com/bwssytems/ha-bridge/releases/download/v2.0.6/ha-bridge-2.5.0.jar"

I realize most users that installing this are probably more Linus savvy than I, and can easily make the needed changes, but it is confusing for us who are not so familiar.

Is there any possibility of changing the instructions to just use something like ha-bridge-latest.jar and then there is no need to update the instructions, or make changes when the version is updated?

**Comment by tinker3433** [comment]
I had issues tracking down what to do regarding the systemctl file. here are my notes. Not sure if i did everything right, but it is working.

Create the directory and make sure that ha-bridge-x.y.z.jar is in your /home/pi/habridge directory. Currently it is 3.1.0, which is shown in the following examples. Change as needed for future versions

     mkdir habridge
     cd habridge
     wget https://github.com/bwssytems/ha-bridge/releases/download/v3.1.0/ha-bridge-3.1.0.jar

Rename the .jar in /home/pi/habridge/
     mv ha-bridge-3.1.0.jar  ha-bridge.jar

Edit the shell script for starting:
     nano starthabridge.sh

Then cut and past this, modify any locations that are not correct
     cd /home/pi/habridge
     rm /home/pi/habridge/habridge-log.txt
     nohup java -jar /home/pi/habridge/ha-bridge.jar > /home/pi/habridge/habridge-log.txt 2>&1 &
     chmod 777 /home/pi/habridge/habridge-log.txt

Exit and save the file with ctrl-X and follow the prompts and then execute on the command line:
     chmod u+x starthabridge.sh

Then execute the script:
     ./starthabridge.sh

You should now be running the bridge. Check for errors:
     tail -f habridge-log.txt

Create a systemctl unit file (habridge.service) so the habridge will autostart:

Create a unit file in the /etc/systemd/system/ directory and make sure it has the correct file permissions. Execute as root:
     sudo su
     touch /etc/systemd/system/habridge.service
     chmod 664 /etc/systemd/system/habridge.service

Open the file for editing
     nano habridge.service

Add the following content to the file:
     [Unit]
     Description=HA Bridge
     Wants=network.target
     After=network.target

     [Service]
     Type=simple
     ExecStart=/usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge.jar

     [Install]
     WantedBy=multi-user.target

Save the file (ctl-o), confirm the file to save as, and exit (ctl-x)

Execute the following commands to reload the configuration and start the custom service:
     systemctl daemon-reload
     systemctl start habridge.service
     systemctl enable habridge

To check the status:
     systemctl status habridge

**Comment by bwssytems** [comment]
Updated

**Comment by Deojuvente** [comment]
not working for me and not knowing what i am doing rong here :(

root@FibaroPI:/etc/systemd/system# sudo su
root@FibaroPI:/etc/systemd/system# touch /etc/systemd/system/habridge.service
root@FibaroPI:/etc/systemd/system# chmod 664 /etc/systemd/system/habridge.service
root@FibaroPI:/etc/systemd/system# cd /etc/systemd/system/cd /etc/systemd/system/
bash: cd: /etc/systemd/system/cd: Bestand of map bestaat niet
root@FibaroPI:/etc/systemd/system# cd /etc/systemd/system/
root@FibaroPI:/etc/systemd/system# nano habridge.service
root@FibaroPI:/etc/systemd/system# systemctl daemon-reload
root@FibaroPI:/etc/systemd/system# systemctl start habridge.service
root@FibaroPI:/etc/systemd/system# systemctl enable habridge
root@FibaroPI:/etc/systemd/system# systemctl status habridge
● habridge.service - HA Bridge
   Loaded: loaded (/etc/systemd/system/habridge.service; enabled)
   Active: failed (Result: exit-code) since ma 2016-10-17 19:23:23 CEST; 10s ago
 Main PID: 1144 (code=exited, status=100)

okt 17 19:23:23 FibaroPI java[1144]: at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
okt 17 19:23:23 FibaroPI java[1144]: at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
okt 17 19:23:23 FibaroPI java[1144]: at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
okt 17 19:23:23 FibaroPI java[1144]: at org.eclipse.jetty.server.Server.doStart(Server.java:384)
okt 17 19:23:23 FibaroPI java[1144]: at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
okt 17 19:23:23 FibaroPI java[1144]: at spark.webserver.JettySparkServer.ignite(JettySparkServer.java:131)
okt 17 19:23:23 FibaroPI java[1144]: at spark.SparkInstance.lambda$init$0(SparkInstance.java:341)
okt 17 19:23:23 FibaroPI java[1144]: at java.lang.Thread.run(Thread.java:745)
okt 17 19:23:23 FibaroPI systemd[1]: habridge.service: main process exited, code=exited, status=100/n/a
okt 17 19:23:23 FibaroPI systemd[1]: Unit habridge.service entered failed state.
root@FibaroPI:/etc/systemd/system#
