### ISSUE TITLE
Add donate button

### ISSUE THREAD

**Issue by ph4x0** [bwssytems/ha-bridge#288]
Hi all together,

I'm using the ha bridge for some month now and I'm very happy that I found this nice piece of software. Due to the high interest of other people in ha bridge and the increased activity here, IMHO would be very nice to have a donate button in the webinterface, just to give something back for the good work.

Just my two cents ...

**Comment by bwssytems** [comment]
Updated at bwssystems.com

**Comment by audiofreak9** [comment]
@bwssytems 
Can you put an id="donate" in the donate form?  I want to put a link to it from my tutorials, so I can direct people straight to the donate button rather than having them scroll to find it.

**Comment by bwssytems** [comment]
Done.

**Comment by bwssytems** [comment]
Thanks @audiofreak9

**Comment by audiofreak9** [comment]
@bwssytems NP!

BTW, "http://bwssystems.com#donate" or "http://bwssystems.com/#donate" both get changed to "http://bwssystems.com/#/donate" and fail to move down your page content to the donate id...bootstrap method?

**Comment by bwssytems** [comment]
@audiofreak9 Ok, issue with mapping in angular js, this should work "http://bwssystems.com/#/#donate"

**Comment by bwssytems** [comment]
Well that didn't work on the target server...angularJs is killing it

**Comment by bwssytems** [comment]
Well not http is used, just the link "bwssystems.com/#/#donate"

**Comment by audiofreak9** [comment]
Ok, so that's not working either.  If I right click and "Open in a new tab" it works.  So I thought add target="_blank", but nope won't work either.   It seems like this is quite a widely discussed "bug" in angular on the web.  Talk about $anchorScroll, but that does not fix linking from my site to yours only internal hash linking. OR You need to 
1. set the `<base href>` without the trailing slash, if set, 
2. configure `hashPrefix`
It all seems not worth the effort for the outcome.
