### ISSUE TITLE
IP address not passed to spark webserver

### ISSUE THREAD

**Issue by disconn3ct** [bwssytems/ha-bridge#292]
If you have multiple addresses, spark tries to listen on 0.0.0.0 instead of just on upnp.config.address:

`2016-12-02 22:47:47,851 [Thread-0] INFO  spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:80`

This prevents it from running if the port is in use by anything else on the system (even on a different address.)

**Comment by bwssytems** [comment]
https://github.com/bwssytems/ha-bridge#web-server-ip-address

**Comment by disconn3ct** [comment]
That only works if the UI can be started (which means stopping all other webservers on the box)

**Comment by bwssytems** [comment]
You can work around it by setting the port number to something else, starting it and then changing the items after. I will look into adding that as a command line override.

**Comment by cogneato** [comment]
I set the port number to 8081, which allowed it to start. But once in Bridge Control changing it to 80 doesn't take. I hit save and the page refreshes and fills in with 8081 again. Do I need to change it somewhere else?

**Comment by bwssytems** [comment]
@cogneato So, your save did not save to the config file. Most likely you have started this where the config file path was not specified to a writable directory and it is using the default path which is not writable. Please look at the read me for specifying the config file path on the command line.

**Comment by noseynovice** [comment]
Hi, I think I'm having the same problem. I originally got the GUI working fine but because Alexa couldn't see my Home Centre devices I went into the Bridge control and changed the UPNP address (don't know why I did that I was just trying anything to get it to work !) and now I can't get onto the GUI for love nor money. 

I get this on the log:

2017-01-07 08:42:50,868 [Thread-0] ERROR spark.webserver.JettySparkServer - ignite failed
java.net.SocketException: Permission denied

I've reinstalled everything on my raspberry pi and deleted from my router firewall an item that was using port 80. I've also run the java -jar -Dserver.port=80 ha-bridge-W.X.Y.jar and changed the port to 90, but no joy. 

I am now in the realms of being totally lost as to what to try now. Any help would be gratefully received ! - have you ever seen a grown man cry ? ;-)

**Comment by bwssytems** [comment]
@noseynovice This does not seem to be your issue yet. you need to start over by deleting your habridge.config file out of your data directory.

**Comment by noseynovice** [comment]
@bwssytems Hi, thanks for your response. Yes I totally started from fresh and all works perfectly now. I have some gold stars from the wife now that she can tell the TV to turn on by voice rather than getting up and using the switch! Many thanks !!
