### ISSUE TITLE
Use Homebridge and/or Apple HomeKit devices

### ISSUE THREAD

**Issue by koraysels** [bwssytems/ha-bridge#366]
You know what would be awesome ?
If we could use all our Homekit accesories (native or via [Homebridge](https://github.com/nfarina/homebridge)) with alexa! 

That way we can use all the available homebridge plugins (which are [many many many](https://www.npmjs.com/browse/keyword/homebridge-plugin) !) so we can comfortably add devices without knowing all the specific udp packets or API calls, relay them to ha-bridge and control them via Alexa!

**Comment by bwssytems** [comment]
Have a look at issue #159 and see if this has any information you may need.

**Comment by koraysels** [comment]
Nope already read that. 
What i mean is the other way around... because Ha-bridge requires you to manually find the udp and/or tcp commands in contrast to homebridge where we use plugins that detect that stuff automatically...

**Comment by bwssytems** [comment]
Would need to take a look at those. I have some other plugins that would be ahead of this for development.

**Comment by koraysels** [comment]
well that would be great! Is there a way others can write plugins for Ha-bridge ? then maybe I could try to port those homebridge plugins to ha-bridge... (homebridge is written in nodejs but hmaybe it has a Plugin API of some sorts.. )

**Comment by bwssytems** [comment]
I have started refactoring the connectors and they are now in the package com.bwssystems.HABridge.plugins

**Comment by Matt8119** [comment]
How do we find and implement and the plugins that you guys are mentioning?

**Comment by bwssytems** [comment]
The classes that are in that package are the examples for implementing other connectors

**Comment by koraysels** [comment]
Cool I'll look into that when i find the time! Thanks for this awesome project @bwssytems ! 

@Matt8119: do you mean "where can i find homebrigde plugins?"  like [these](https://www.npmjs.com/browse/keyword/homebridge-plugin)?) Or do you mean "where can I find Plugins for ha-bridge? -> I guess they are none except the ones included already in the project.

**Comment by Matt8119** [comment]
That's exactly what I was talking about. I misunderstood and thought these were already inside the jar, located inside its own folder.. that answered my question. Thanks!

**Comment by bwssytems** [comment]
Is your question answered?

**Comment by koraysels** [comment]
No .. the highjacked question was answered but not my original question:) anyway looking forward to 4.0

**Comment by pponce** [comment]
+1 for being able to leverage homebridge plugins

**Comment by bwssytems** [comment]
So, won't be able to implement plugins from homebridge since it is written in javascript and we are pure Java, also that is a specific interface set for homebridge. I'm looking into being able to call the homebridge (it may allow it ti call apple homekit, but may not either) and deal with it that way. It is very intensive reverse engineer the client side (Homebridge and it's libraries are the server side) as all of the info that was written had to be taken down due to an Apple lawsuit. The code is all that is left to decipher.

**Comment by Hedda** [comment]
Apple have now opened HomeKit protocol specification to all developers for non-commercial use:

https://www.appleworld.today/blog/2017/6/7/apple-opens-homekit-protocol-specification-to-all-developers

"HomeKit protocol spec is now open to all devs! Can build a smart device using Arduino and control it via HomeKit without getting MFi license."

https://developer.apple.com/homekit/specification/

That is, this is the Apple official HomeKit protocol specifications, and Apple want third-parties to use it.

**Comment by bwssytems** [comment]
Great! Now I can figure out my issues with session security handshake!

**Comment by Hedda** [comment]
HomeKit for iOS 11 will have a few new features too, as summerized here:

https://www.theverge.com/2017/6/8/15761800/apple-homekit-updates-ios-11-easier-build-requirements-wwdc-2017

"On top of these updates to make building HomeKit devices easier, Apple is also expanding what HomeKit can do in ways that consumers will notice. It's adding two new categories of supported products, sprinklers and faucets, and it's adding a bunch of new ways to trigger actions at home.

One of the simpler updates, but a favorite of mine, is an enhancement to the sunrise and sunset triggers. Those can now be offset by some amount of time, so you could, for instance, have the lamps in your home turn on shortly before the sun goes down at night.

Apple is adding temperature triggers, too, so that events can be kicked off when the temperature goes above or below a certain point. And it's getting better at tracking when people are in the house. It'll now track specific people, instead of individual devices, and use that to better tell you when someone leaves or arrives home. In iOS 11, that'll allow HomeKit users to set things to happen when the last person leaves the house or when someone's arriving home to an empty house.

There will also be a way to temporarily turn on certain devices. Apple gave the example of opening a door at night and having outside lights turn on for just a few minutes, instead of turning on and staying on as they’d have to currently."

**Comment by dmoos777** [comment]
Would be so wonderful if this would work with Apple Homekit.  This would allow me to have everything in one place.

**Comment by bwssytems** [comment]
This is also mentioned in #822

**Comment by bwssytems** [comment]
With the implementation of Mozilla IOT, Which has homebridge connectivity, I will suggest that is the path to implement this.

See https://iot.mozilla.org/
