### ISSUE TITLE
Error running scripts

### ISSUE THREAD

**Issue by Rob78** [bwssytems/ha-bridge#373]
I have created a script called computer-on.sh I manually add a new device

I am using docker container ha-bridge
Name: computer
device type: execute script/program
on url: /home/username/WOL/computer-on.sh

when I click Test ON button I get an error that says" Request Error. Plese look in your habridge log: error {"type":6,"address":"/lights/1":"description":"Error on calling out to device","parameter":"/lights/1state"}

computer does not turn on.  Computer does turn on if I ssh into ubuntu and run computer-on.sh

any ideas?

**Comment by audiofreak9** [comment]
Does you bash script run without using the sh or bash commands?

To run a bash script without these commands you need to:

1. Have the shebang #!/bin/bash on the very top.
2. Chmod u+x computer-on.sh make the script executable.

If not try:

`on url: sh /home/username/WOL/computer-on.sh`

**Comment by Rob78** [comment]
I have done both 1 and 2 but still no luck

I am no expert on linux but I think I know what the problem is. I have noticed I am unable to do any commands that require sudo. For example running sh scripts from ssh I need to sudo. rinning etherwake I require sudo. I will need to figure out how to allow ha-bridge to launch sh files as root

**Comment by Matt8119** [comment]
@Rob78 follow this guys youtube video installing the ha-bridge.  he has two videos. neither video of the video he talks, but you can follow along his steps, being you need exactly what hes doing.  hes using the Vera hub, but its the exact same process for all smart hubs.  https://www.youtube.com/watch?v=3xoQTUJEH2I

**Comment by bwssytems** [comment]
Is this resolved?

**Comment by kennyhq** [comment]
I have the same issue thus not resolved.

Thanks,

Kenny

**Comment by pr3sidentspence** [comment]
I think I got this once when I accidentally got the path to my shell script
wrong. "/habridge/script.sh" instead of "/home/pi/habridge/script.sh" in my
case.

**Comment by bwssytems** [comment]
@kennyhq What is your issue? Is it running scripts as root?

If running a script and it needs root access for something, you should rework the script so that the items that are needed are chrooted to the user that needs it.

This is not an ha-bridge issue.

**Comment by kennyhq** [comment]
Attached is the image with my setting.  The script is executable and i put it in /tmp so it is accessible by everyone ..
Please check the screen shot.

At the top of the screen shot, there is an error message when I execute Test On button test before coming back to the editing page.

![screen shot 2017-01-23 at 2 32 02 pm](https://cloud.githubusercontent.com/assets/6855060/22225834/e3446968-e178-11e6-9e33-6dd860b4e84a.png)

**Comment by bwssytems** [comment]
@kennyhq We will need to see the log file for the error

**Comment by kennyhq** [comment]
Below is log snippet I have from syslog which ha-bridge is written to.. i filtered it out when I attempt to click on the button Test On:




Jan 23 22:40:27 raspberrypi java[10647]: 2017-01-23 22:40:27,949 [qtp23929096-22] WARN  com.bwssystems.HABridge.hue.HueMulator - Error calling out to HA gateway: IOException in log
Jan 23 22:40:27 raspberrypi java[10647]: org.apache.http.client.ClientProtocolException: null
Jan 23 22:40:27 raspberrypi java[10647]: at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
Jan 23 22:40:27 raspberrypi java[10647]: at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
Jan 23 22:40:27 raspberrypi java[10647]: at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
Jan 23 22:40:27 raspberrypi java[10647]: at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
Jan 23 22:40:27 raspberrypi java[10647]: at com.bwssystems.HABridge.hue.HueMulator.doHttpRequest(HueMulator.java:1290)
Jan 23 22:40:27 raspberrypi java[10647]: at com.bwssystems.HABridge.hue.HueMulator.lambda$setupServer$39(HueMulator.java:1135)
Jan 23 22:40:27 raspberrypi java[10647]: at spark.RouteImpl$1.handle(RouteImpl.java:58)
Jan 23 22:40:27 raspberrypi java[10647]: at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
Jan 23 22:40:27 raspberrypi java[10647]: at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.server.Server.handle(Server.java:517)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
Jan 23 22:40:27 raspberrypi java[10647]: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
Jan 23 22:40:27 raspberrypi java[10647]: at java.lang.Thread.run(Thread.java:745)
Jan 23 22:40:27 raspberrypi java[10647]: Caused by: org.apache.http.ProtocolException: Target host is not specified
Jan 23 22:40:27 raspberrypi java[10647]: at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:70)
Jan 23 22:40:27 raspberrypi java[10647]: at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:124)
Jan 23 22:40:27 raspberrypi java[10647]: at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:183)
Jan 23 22:40:27 raspberrypi java[10647]: ... 23 common frames omitted
Jan 23 22:40:27 raspberrypi java[10647]: 2017-01-23 22:40:27,950 [qtp23929096-22] WARN  com.bwssystems.HABridge.hue.HueMulator - Error on calling url to change device state: /tmp/test.sh

**Comment by bwssytems** [comment]
@kennyhq please read the instructions: https://github.com/bwssytems/ha-bridge/blob/master/README.md#script-or-command-execution

**Comment by kennyhq** [comment]
Yes I followed the instructions also placing the same script in ~ home directory also changing permissions to root etc..   note: ha-bridge is running as system service thus own by root.

Please tell me what I did wrong.

Kenny

**Comment by bwssytems** [comment]
It's how you formatted the request... It CV is exec://(script path)

**Comment by bwssytems** [comment]
@kennyhq Let's try the new version. It has better device handling.

**Comment by kennyhq** [comment]
I'll try new version.  

Adding exec:// to the path of the script works perfectly.  The document does not state that I need to add exec://  except inside multiple items -  maybe some notation in the doc/readme to have "exec://" prepend the path - just a suggestion.

Thank you so much for your help,

Kenny

**Comment by Rob78** [comment]
It is working for me as well. This version 4 is great. Thank you for your hard work and the help you have given us. I was having trouble with docker but I went away from it. I am now using HA Bridge as a service to autostart. Thanks again

-Robert

**Comment by kennyhq** [comment]
Version 4 works great.  

I have a suggestion to make:

I have ha-bridge to execute a list of commands (local scripts) with a delay of 3-5 seconds.  Total delay time is around 10 seconds to get to the final command to execute.  Alexa works great if total time is less than 5 seconds.  If it's above 5 seconds, Alexa will say "sorry the device *name* is not responding.."  yet all commands would get executed. 

Is it possible to configure ha-bridge to return success back to Alexa calls right away, even there are pending commands?


Real life scenerio:

Turn on LG TV
Turn on Direct TV  (delay 8000 ms)
Make LG TV switch to HDMI2  -(custom script to do this)

The delay is needed   for TV to startup complete first before HDMI2 can be issued.


Regards,

Kenny

**Comment by bwssytems** [comment]
That is something that is requested in issue #341

**Comment by Rob78** [comment]
I am going to close this issue since the main issue we were having has been solved.

Thanks again.
