### ISSUE TITLE
Resize Target Item Field

### ISSUE THREAD

**Issue by lonebaggie** [bwssytems/ha-bridge#381]
Just upgraded to Version 4. With all the new  field options on the add device, the target item field width is very small .  The target item field  has the payload for all my UDP calls which are  at least 40 characters long.

Took me a while to figure out how to increase the width. Would it be possible for the program to remember the new field width size , or an option to change the default width , just to make my configuration more readable ? 

If not can the pull down menus be shortened as they are much longer then required ?

Very, very  minor issues but it just stumped me for a while. 

Glad to see the donate option, this program is brilliant and deserve support many thanks

**Comment by bwssytems** [comment]
There is a size request in the code, but due to the dynamic nature for sizing from angular, it may not use it as to fit all the fields as you are seeing.

**Comment by tuicemen** [comment]
I think if all fields for on/off and dim items rows were made the same initial size it would be more user friendly.
At least it would allow new users to read the titles as it is now they're guessing at some.

**Comment by darnold64** [comment]
How do you change the column / row sizes...I tried everything...no luck.  I reverted to version 3.5.1 to set everything up because I found it so hard to add things in version 4.5.0 since the target item field in my MS Edge browser is only about a character wide.

**Comment by bwssytems** [comment]
Ahh, use chrome. It will show the resize handle on the fields

**Comment by FloFoer** [comment]
I got annoyed by the uniform auto resize too and i handled it that way:  
Simply change editdevice.html so that the single columns have appropriate "min-width" css attributes. That way you can forbid the "target item" field to get smaller than a specified still useful minimum. Of course thats anti responsive thinking, but please, who configures ha-bridge with anything with a small screen. I also applied some max-widths for fields like "delay", because these really don't have to be that big and with that there is more room available that could be used elsewhere better.
