### ISSUE TITLE
MQTT issues with 4.0.3

### ISSUE THREAD

**Issue by firecube** [bwssytems/ha-bridge#409]
Hi,

I am having issues with 4.0.3 where none of my MQTT messages are being sent when testing the devices.  I have removed and re-added my devices and also spun up a new docker instance.

The logs show...

Decode Json for url items: [{"item":"{\"clientId\":\"habridge\",\"topic\":\"homie/amp/power/on/set\",\"message\":\"false\"}","type":"mqttMessage"}]
executing HUE api request to send message to MQTT broker: "{\"clientId\":\"habridge\",\"topic\":\"homie/amp/power/on/set\",\"message\":\"false\"}"

Which is the right data but that message is not received.  I also see the following in a temporary message in the top right of the screen which is not related to the message I am sending.

Request Executed: success {"/lights/1/state/on":false}

Thanks, Simon

**Comment by ademobile** [comment]
I've had this issue since trying 4.0.1, I get no MQTT messages over the network when running 4.0.1, 4.0.2 or 4.0.3. Running 3.5.1 no problem. I have MQTT spy running with a # filter running and NO messages are sent. I did report this on 4.0.1 and it was labelled as bug and close, however issue still remains.

I have done a complete rebuild of all my devices and cannot get any output. It does register with my MQTT server, but thats all

**Comment by bwssytems** [comment]
Will look into

**Comment by bwssytems** [comment]
Verified. Loop control construct never goes and executes call.

**Comment by firecube** [comment]
Hi,
Initial testing is looking good.  Thanks so much for the really quick turn around!

The message in the UI when testing on and off still looks to be hard coded with... Request Executed: success {"/lights/1/state/on":false}... but this is only a minor thing.

Thanks again for a great piece of software.
Simon
