### ISSUE TITLE
Assistance with creating a HTTP request

### ISSUE THREAD

**Issue by mickesanda** [bwssytems/ha-bridge#465]
Hello,
This is a question from a n00b trying to send a HTTP-string to a smarter coffee machine.
The ibrew server/bridge is installed on 192.168.0.30:2080.
I want to create a device in HA-Bridge which sends this string: 
http://192.168.0.30:2080/brew/5/6/beans/strong
Sorry if this is a stupid question, but I do not understand how to populate the fields in the attached picture.
![habridgedevice](https://cloud.githubusercontent.com/assets/25711701/22877960/0b788b2a-f1d8-11e6-8257-92b8c91eee1d.JPG)

Thank you in advance,
/Mike

**Comment by jbardi** [comment]
Don't worry about Target, Device Type or Map Type at the top.

In the "On Items" row, set "Type" to "HTTP Device", then in "Target" put your URL "http://192.168.0.30:2080/brew/5/6/beans/strong", then set "Http Verb" to "GET", since you have no JSON header or body data to post, in which case you would have set it to "POST" instead of "GET", now, since I don't know what response is coming back from your coffee maker (if any), so I would set "Content Type" to "*/*", and that should be it. Just remember to hit the "Add" button at the far right of the row so it sets your data, and then hit the "Add Bridhe Device" button at the top and you are done.

**Comment by jbardi** [comment]
For clarification, your URL goes in the "Target Item" field of the "On Items" row, but I said "Target" by mistake, so I don't want you to get confused with the "Target" field at the top that I said you can skip.

**Comment by mickesanda** [comment]
Thank you for your fast response, it was very clear.

 

Michael Sanda

micke@sanda.nu <mailto:micke@sanda.nu> 
+46(0) 709 75 96 69

 

 

 

Från: jbardi [mailto:notifications@github.com] 
Skickat: den 13 februari 2017 13:20
Till: bwssytems/ha-bridge <ha-bridge@noreply.github.com>
Kopia: mickesanda <micke@sanda.nu>; Author <author@noreply.github.com>
Ämne: Re: [bwssytems/ha-bridge] Assistance with creating a HTTP request (#465)

 

Don't worry about Target, Device Type or Map Type at the top.

In the "On Items" row, set "Type" to "HTTP Device", then in "Target" put your URL "http://192.168.0.30:2080/brew/5/6/beans/strong", then set "Http Verb" to "GET", since you have no JSON header or body data to post, in which case you would have set it to "POST" instead of "GET", now, since I don't know what response is coming back from your coffee maker (if any), so I would set "Content Type" to "/", and that should be it. Just remember to hit the "Add" button at the far right of the row so it sets your data, and then hit the "Add Bridhe Device" button at the top and you are done.
