### ISSUE TITLE
Adding a device (url)

### ISSUE THREAD

**Issue by chrisklpp** [bwssytems/ha-bridge#471]
Hello,
my aim is to include a fhem trigger into ha-bridge. I want to make ha-bridge opening a link on an alexa voice command. 
I followed a tutorial and the essential point is given in this screenshot:
![habridge_config](https://cloud.githubusercontent.com/assets/25778747/22947739/7786fc6e-f2fc-11e6-8e72-722f01864406.png)

Now my problem is, that in my ha-bridge I don't get that ui, but only this entry field:
![unbenannt](https://cloud.githubusercontent.com/assets/25778747/22947673/4488b244-f2fc-11e6-868f-898a47dbab3a.JPG)

Am I doing completly wrong or is this related to the ha-bridge version?

Can you help me?

Thanks a lot!

**Comment by bwssytems** [comment]
So now in the On Items area the Type will be HTTTP Device and the Target Item is the URL.

**Comment by hernandito** [comment]
Hello, I am posting here since it is a similar question:

I want to configure a device that basically sends an request to my **Kodi** machine. In this example, if I enter the URL code below into any web browser, in my Kodi machine, it launches an Artwork Downloader (add-on) search:


http://myusername:mypassword@192.168.0.103:88/jsonrpc?request={%20%22jsonrpc%22:%20%222.0%22,%20%22id%22:%200,%20%22method%22:%20%22Addons.ExecuteAddon%22,%22params%22:%20{%22addonid%22:%20%22script.artwork.downloader%22,%20%22params%22:%20{%22mediatype%22:%20%22movie%22}}}

For the life of me, I cannot figure out how to configure HA-Bridge. Please see screencap below:

![image](https://cloud.githubusercontent.com/assets/787317/23221982/7d546a8e-f8f4-11e6-9ce8-ecbbd3053757.png)

After adding this, I was able to detect the device name in my Alexa app - but obviously it did not work.

On a similar note, I want to be able to also send a command that executes a php and/or sh script on my server. my server has an internal ip of **192.168.1.200** (HA-Bridge runs in a Docker on this server), I would want to execute a command like:

` php /config/www/script.php`

and/or

`sh /home/script.sh`

Unfortunately I could not find anything that provided samples. 

Any advice is greatly appreciated.


Thanks,


H.

**Comment by bwssytems** [comment]
Is this resolved from the other issue that was opened?
