### ISSUE TITLE
turning off harmony activity

### ISSUE THREAD

**Issue by cipher2k** [bwssytems/ha-bridge#497]
Is it possible to turn off a specific harmony activity and not only use the PowerOff (-1) activity for all?

**Comment by rafale77** [comment]
Not sure what you are trying to do. Do you have activities for one given hub which control completely independant devices (activities 1 involve A-B-C and activity 2 involve E-F-G?). I think the Harmony hub was designed to control on hometheatre at a time so only one TV, one Receiver, multiple sources... It isn't so much of an HAbridge hub question, It is more of how the Harmony hub was designed. If you do have multiple independant activities, best way is to use multiple hubs... The harmony hub is only designed to be in Activity 1, Activity 2 etc or off state. It was not designed to have activities 1 and 2 running concurrently for example.

**Comment by cipher2k** [comment]
Well, that is not entirely true. There was a conversation few months ago regarding this:

https://github.com/bwssytems/ha-bridge/issues/54

But it was closed due to the topic opener was not interested anymore in the solution.

Digging the internet few weeks ago regarding the Harmony API I stumbled across a fork on github were someone has managed to identify and implement the correct "end" or "stop" activity command. So it must exist. But, I have lost it.

**Comment by bwssytems** [comment]
@cipher2k That is actually my fork and I have not found any end activity item as of yet. It is still considered poweroff -1 to end the activity, or you just select the next activity you want. That is all my ultimate remote shows me anyway.

**Comment by rafale77** [comment]
It is my understanding anyway that the hub only has one activity state and not one state per activity so you cannot turn an activity on and off. The state is an activity number or off (-1). It is designed that way so that when you switch from one activity to another, it easily switches the appropriate devices to that target activity without power cycling each device. (switching inputs, turning the target sources on, and the others off)

**Comment by cipher2k** [comment]
I understand. I found something else:

https://docs.google.com/document/d/1fjPMr0eLJWaFoZw0JMu449dgKFXR0K1m6EoxsDbgt8I/pub

It seems to be some kind of an official Harmony API document. There is this sentence that puzzles me somehow:
"Start an Activity. If the Activity is an AV Activity, the hub's current AV Activity (if any) will be ended. Starting a non-AV Activity does not affect the current AV Activity."

And right below it there is "end activity" request.... Does anyone know this document? I found via google.

**Comment by rafale77** [comment]
I think this was related to the newer version of the hub firmware where light controls were added to the hub. There might be some non AV activities but I have never used it since all my non AV devices are controlled by another system. Would have to find out how to define an activity as being AV or non-AV.

**Comment by bwssytems** [comment]
that document is for the cloud api. what is being used is the local api, which is in xml requests. the end activity is something special for non av setups. not sure how that is used
