### ISSUE TITLE
hass HA bridge idle problem

### ISSUE THREAD

**Issue by erroldee** [bwssytems/ha-bridge#501]
the latest code release has almost fixed the hass and ha bridge connection. although there is still a minor problem happening when the connection is idle.

when given a command after a period of idle time the first command will always fail. any succeeding command after that will be successful. give it another few minutes of idle time and it repeats, failing the first command after idle then succeeding commands will be successful. around 2-3 minutes of idle time for me.

**Comment by jbardi** [comment]
Weird, I have not experienced this issue since my update. I am now able to use it with Home Assistant without any issues so far.  Although, all of my Home Assistant calls are using Home Assistant's direct RESTapi rather than the Home Assistant helper, so not sure if this is just in issue when using the helper? Just thought it might help for them to pinpoint the problem you are having so they can find a fix. I'm going to let it run for 24 hours and see if I have any issues. So far, it looks like the hanging issues I was having previously that made it appear as habridge was locking up has now been fixed, but again, I'll give it 24 hours to see if I have any problems, as I would normally not have been able to go a couple hours before it started having trouble.

**Comment by erroldee** [comment]
am using the same. rest API for better control. am using http device type on ha bridge. will also monitor for 24 hours and report back if this improves or worsens but as of writing this i am still encountering the issue

**Comment by erroldee** [comment]
here are some screenshots of the error i am seeing when this happens

![screenshot_20170226-051328](https://cloud.githubusercontent.com/assets/340534/23334850/a87bc4e6-fbe2-11e6-86a8-c92bc4b4268c.png)

![screenshot_20170226-051259](https://cloud.githubusercontent.com/assets/340534/23334859/cd8abc06-fbe2-11e6-99d0-106f50aebd3a.png)

**Comment by bwssytems** [comment]
i could put in a retry if the timeout is receiced

**Comment by erroldee** [comment]
that could work. still seeing the same issue as of writing. have tried rebooting pi multiple times.

**Comment by erroldee** [comment]
still occurring so i implemented the retry work around when receiving 504 status code and it worked great! thanks!

**Comment by bwssytems** [comment]
I will put the retry in the code

**Comment by brandoncorry** [comment]
I'm still seeing these issues with 4.3.1. Pretty much every morning I have a scene I turn on, and it will always fail, and I have to try it again. I can see it retrying, but it retries and then says the call fails. When I try again it works as expected.. not sure if this is a HA-Bridge problem or a Home Assistant problem... but thought I'd add to this issue to see if others are experiencing it so we can figure it out..

![image](https://cloud.githubusercontent.com/assets/17894275/24580328/0ab4e104-16bb-11e7-9d35-d01f1d5a22f0.png)
