### ISSUE TITLE
HA bridge commands are worse understood than normal Alexa commands? - German issue?

### ISSUE THREAD

**Issue by Wolkex3** [bwssytems/ha-bridge#514]
HA bridge commands are worse understood than normal Alexa commands. For example, I say "turn five on", alexa then always asks in the best case what device I mean and I must repeat five.

If I say, "Alexa what is five plus one", Alexa understands it immediately and answers "six".

I speak german btw. 

Am I the only one with this problem?

**Comment by bwssytems** [comment]
There is no understanding by the ha-bridge... You control what Alexa uses as the keyword by setting the name field in the ha-bridge.

**Comment by Wolkex3** [comment]
That is really crazy. I can repeat that thousand times.

As if some HA-Bridge commands would be worse understood.

"Turn TV on" works perfectly. But "turn five on" never works on first try.

**Comment by bwssytems** [comment]
That is Alexa interpreting that word for your device "five". The ha-bridge emulates the hue api which alexa communicates with, there is no interpretation by the ha-bridge. I would let amazon know they have an issue.

**Comment by Wolkex3** [comment]
Okay, I already sent feedback.

Thank you for your great work!

**Comment by rafale77** [comment]
My guess is that Alexa actually interprets it perfectly and is not sure what you are trying to do when you say 'turn "5" on' because it means something to the engine. When naming your devices, one should avoid using names which could mean something to Alexa. One example is, if you ask Alexa to turn on Alarm or music or volume, with a device named that way, it will not work...

**Comment by Wolkex3** [comment]
Commands: "Turn 1 on", "Turn 2 on", "Turn 3 on", "Turn 4 on" are "Turn 78 on" working. 

It is really hard to create commands. E.g. anything with "loudness" doesnt work. 
Are there any hints, how to create commands in the best way? 

I originally wanted to say "turn ARD on" (german TV like A.R.D) but this commands failes everytime. That is why I tried to choose the tv channel number 1.

**Comment by merlin051** [comment]
I tried having a device named HDMI2 but instead opted for just calling it Kodi as it wasn't working

**Comment by bwssytems** [comment]
Closing as this is an Amazon topic

**Comment by bwssytems** [comment]
@Wolkex3 You could use the ${intensity.percent} so that you could say "Alexa, set thing to 70" and it would call the dim command in the ha bridge fro that device.

**Comment by Wolkex3** [comment]
Ah @bwssystem, that is a really good hint!

I have a lot of small python scripts. They just call the lirc commands. 

I will check how I can implement this. Thank you!

**Comment by bwssytems** [comment]
You can use the ${intensity.percent} replacement variables as the arg to your script in the exec comman:

exec://change.sh ${intensity,percent}

**Comment by Wolkex3** [comment]
Okay, I have a shell script called channel.sh, which can get one argument for the tv channel. 

I tried it in the terminal and it works with: sh channel.sh 5  
But I have problems to execute it with ha-bridge.
/home/pi/echo/tv/channel.sh 

I get following message
"Request Error, Pleae look in your habridge log: error {"type":6,"address":"/lights/10","description":"Error on calling out to device","parameter":"/lights/10state"}"

What do I have to set in the dim line @ha-bridge?

TIA!

**Comment by Wolkex3** [comment]
From devices:
"Fernseher","mapType":"cmdDevice","deviceType":"custom","offUrl":"[{\"item\":\"/home/pi/echo/tv/fernseher_onoff.py\",\"type\":\"cmdDevice\",\"httpVerb\":\"POST\",\"contentType\":\"*/*\"}]","dimUrl":"[{\"item\":\"/home/pi/echo/tv/channel.sh ${intensity.byte}\",\"type\":\"cmdDevice\",\"httpVerb\":\"POST\",\"contentType\":\"*/*\"}]","onUrl":"[{\"item\":\"/home/pi/echo/tv/fernseher_onoff.py\",\"type\":\"cmdDevice\",\"httpVerb\":\"POST\",\"contentType\":\"*/*\",\"delay\":\"20\"}]","inactive":false,"noState":true,"deviceState":{"on":false,"bri":0,"hue":0,"sat":0,"effect":"none","ct":0,"alert":"none","reachable":true}}]

**Comment by Wolkex3** [comment]
I tried this too:  
exec://home/pi/echo/tv/channel.sh ${intensity,percent}

**Comment by Wolkex3** [comment]
Log:
 	Could not execute request: home/pi/echo/tv/channel.sh ${intensity,percent}

**Comment by bwssytems** [comment]
You need another slash as it is trying to execute from a subdir called home....

exec:///home/pi/echo/tv/channel.sh ${intensity,percent}

**Comment by Wolkex3** [comment]
Tried 
exec:///home/pi/echo/tv/channel.sh ${intensity,percent}
but I get this:
Could not execute request: /home/pi/echo/tv/channel.sh ${intensity,percent}

**Comment by audiofreak9** [comment]
Should be a period between intensity and percent, not a comma.

**Comment by Wolkex3** [comment]
Thank you for your help @audiofreak9 and @bwssytems. I tried a period too, but I get the same error.

If I try it with terminal the script works "pi@raspberrypi:~/echo/tv $ sh channel.sh 5"

**Comment by digiltd** [comment]
Some general tips I find help when naming things are...

Avoid single syllable words, especially when there is no context. I also agree with @rafale77 in thinking numbers are probably best avoided due to potential conflicts with native alexa stuff.

But there is no harm in having a number and another word e.g. "turn on channel five" "turn station five off" 

The Harmony Hub might be worth looking into, the hub and ha-bridge work very well together :)

For your A.R.D channel issue, or any other time you want to spell out letters the Amazon advice is either have it in all caps with no space "ARD" or lowercase with dots and spaces "a. r. d. ".

[https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#h3_intentref_rules](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#h3_intentref_rules)
> * Numbers should be expressed as words and not digits (“five”, not “5”).
> * Acronyms and other phrases involving spoken letters should be separated by periods and spaces (“n. b. a.”, not “nba”).
> * Punctuation marks should not be included except in the special cases listed below. (“ten dollars”, not “$10”. “three point five stars”, not “3.5 stars”). Exceptions:
>    * Include periods after letter abbreviations (“n. b. a.”, “e. t. a.”).
>    * Include apostrophes in possessive and contractions (“romeo’s” and “i’m”).
>    * Include hyphens that are word-internal (“man-eating”) but in no other cases.

I use "HDMI One" and "HDMI Two" with ha-bridge with no problems.

Be creative, i found she often had trouble when I would say "turn the projector off" (she would always start a "chapter" in an audio book). So I change it to "turn the big screen off" :)

The last tip is to let her know when she does the right thing. In the Alexa app it really does help her better understand you when you answer yes or no to the "Did Alexa do what you wanted?"  question.

Not sure if why I am adding this, but I found it interesting and others might as well. I was trying to give support to someone using the Kodi Skill and their problem with it not understanding the "eject" command. I am in the UK and I could not get it to recognise me saying eject at all, it would always think I was saying "check"

* ask kodi to be checked c. d.
* ask kodi to check the cd
* ask kodi to check to see
* ask kodi to check the rain
* ask kodi to check

The Americans were also having trouble, Alexa was hearing "jack" not "check". 

A quick experiment and it was clear why the two were hearing the same word differently :)  

https://clyp.it/5jyn1w2g (three UK voices then three US voices)

**Comment by audiofreak9** [comment]
@Wolkex3 
Have you made the bash script executable?

**Comment by Wolkex3** [comment]
Hi @audiofreak9,
this is the shell-script:

#!/bin/sh,
irsend SEND_ONCE /home/pi/lircd.conf KEY_$1

and I have executed this command in terminal: sudo chmod +x channel.sh

**Comment by audiofreak9** [comment]
Try `sh /home/pi/echo/tv/channel.sh ${intensity.percent}` instead (or "bash" in place of the "sh" prefix, depending on the script type).

**Comment by Wolkex3** [comment]
sh is working, thank you very much @audiofreak9! 👍
