### ISSUE TITLE
Question Volume

### ISSUE THREAD

**Issue by merlin051** [bwssytems/ha-bridge#534]
Hi. Question for anyone with similar setup.

How do you handle volume?

I have a sound bar and I'd like to be able to use Alexa to turn the volume up. I have a broadlink em pro linked into my setup and was wondering about using the {intensity} variable​ to try and control this.

What is everyone else doing?

Making a device called [Volume Up/Down] and have Alexa turn it on repeatedly seems silly.

**Comment by audiofreak9** [comment]
Remember that "Volume" is a reserved word for the Echo.  I use "Sound" instead for my home theater volume.

**Comment by merlin051** [comment]
My device is called [Sound Bar] which Alexa gladly turns it on/off with the assistance of an RmPro/MQTT/HA-Bridge.

i'm thinking i might need a script which can accept the {intensity} argument and then send(several) from MQTT values for my RMPro.

I suppose I'm after advice of someone who has done a similar task. I'm not sure if the following would be the way forward....

"Alexa set [Sound Bar] to 70%" -- run volume up script

"Alexa set [Sound Bar] to 20%" -- run volume down script

**Comment by digiltd** [comment]
Have a look at the wiki as there is a section on controlling volume in Kodi that might inspire.

Problem with IR volume control is all it can do it press a button. I had a play and wrote a simple for openhab where if I said "set yamaha sound to 60%" it would read the 60 but because 60 button presses is too many button presses 😴  it divided the number and then sent out the presses using Harmony.

It was pretty 💩 

"Alexa, set yamaha sound to 60%"

(wait 10 or seconds while most of the presses are not registering)

"Alexa, set yamaha sound  to 40%"

(wait wait wait)

Adjusting the volume level is something you need to accurate control of. If you have a network connected amp you can sent the direct value, the old IR method is best avoided. It isn't worth the trouble. 

The Harmony Skill does allow "Alexa, ask harmony to turn the volume up" which I use occasionally, and I use toggle mute with Alexa and ha-bridge and that works fine and is worth setting up.

Here is my openhab rule I used but i wouldn't recommend it ;)

````
rule "Harmony_Volume_Presses Up"
when
    Item Harmony_Volume_Presses_Up received command
then
        var i = 0
        var Number num_BtnPresses = receivedCommand

       
        logDebug("num_BtnPresses Up", num_BtnPresses.toString())
        num_BtnPresses = (num_BtnPresses * 50 / 100).intValue  //Scale percentage of volume to Monoprice scale (0 to 38)
        logDebug("num_BtnPresses Up Scaled", num_BtnPresses.toString())

        while((i=i+1) <= num_BtnPresses) {
                harmonyPressButton("Amp", "VolumeUp")
                logDebug("loop", i.toString())
                Thread::sleep(100)
            
        }
end

rule "Harmony_Volume_Presses Down"
when
    Item Harmony_Volume_Presses_Down received command
then
        var i = 0
        var Number num_BtnPresses = receivedCommand

        logDebug("num_BtnPresses Down", num_BtnPresses.toString())
        num_BtnPresses = (num_BtnPresses * 50 / 100).intValue    //Scale percentage of volume to Monoprice scale (0 to 38)
        logDebug("num_BtnPresses Down Scaled", num_BtnPresses.toString())


        while((i=i+1) <= num_BtnPresses) {
            harmonyPressButton("Amp", "VolumeDown")
            logDebug("loop", i.toString())
            Thread::sleep(100)
        }

end
````
