### ISSUE TITLE
How to run Fibaro Scene in HA-Bridge?

### ISSUE THREAD

**Issue by chchiat** [bwssytems/ha-bridge#560]
Hi,

I tried to fill in the scene control command to HA-Bridge. But it does not work.

http://USER%40EMAIL.COM:PASSWORD@IPADDRESS/api/sceneControl?id=ID&action=start

I tried to fill in the scene control link to the "On Items" field in HA-Bridge, it does not work. But I tried to run in my browser it works.

How should we fill it if we want to run a scene in HA-Bridge?

Anyone? Thanks.

**Comment by Matt8119** [comment]
the fibaro commands are a little bit different and change with updates... with the last major update, you need to add an extra "/" between address and api like the example below:
http://USER%40MAIL.COM:PASSWORD@IPADRESS//api/devices/17/action/turnOn

**Comment by chchiat** [comment]
Hi Matt,

Can I assume if I want to trigger a Scene I should put in the http command below into "On Items" field in Ha-bridge?

http://USER%40MAIL.COM:PASSWORD@IPADRESS//api/sceneControl?id=45&action=start

Am I right?

**Comment by chchiat** [comment]
tried with the two "//" does not work.

**Comment by autofrank** [comment]
Hi

I have used 
`http://	USER%40EMAIL.COM:PASSWORD@IPADDRESS/api/sceneControl?id=ID&action=start`

to start a scene with the latest HA bridge and it works
replace ID with scene id

**Comment by qnstie** [comment]
In the current Fibraro firmware (4.140) the API call is:
`http://FIBARO_IP/api/scenes/16/action/start`

You may try to add the `user:password@` prefix before the IP to pass the parameters.
But:

Generally there is a real problem with Fibaro is with using the http://user@password@IP/API_CALL, which manifests itself when you try to pass JSON arguments in the HTTP body (like with a dimmer, where you need to pass a `{"args":[${intensity.percent}]}` JSON to the Fibaro API call (`/api/devices/DEVICE_NUM/action/setValue`).
With the current Fibaro firmware such a call will always result with error 405.

Mercifully a simple solution exists and I guess it is generally better than using the username and password.

All you need to do is to - instead of the `user:password@` construction - use a HTTP header with a hash of the user:password part.
You just add a block like below to the "HTTP Headers" section of the HA Bridge definition:
`[{name: "Authorization", "value": "Basic XYZaaaaaaaaaabbbbbbccc=="}]`

The content of the XYZ... block above can be generated in a few seconds by many tools, take the first one in Google (search for e.g. "authorization: basic hash generator"). I personally use Postman Chrome extension (a great tool to test REST calls), which has the hash generator built-in.

I use the above HTTP header solution for all the calls (even without parameters), it seems a much cleaner and safer solution than using user and password in unencrypted HTTP call.

**Comment by bwssytems** [comment]
Fibaro Scenes will be included in 5.0.0
