### ISSUE TITLE
Anyone know commands for LG TV?

### ISSUE THREAD

**Issue by crsnwby** [bwssytems/ha-bridge#637]
I can see a WebOS 3 TV can be controlled using python, is there any way of controlling it using ha-bridge?

Tried using the xml but dont know what im doing

?xml version="1.0" encoding="utf-8"?
envelope
api type="command"
        nameHandleKeyInput/name
        value21/value    #21 being the remote code for HOME button
    /api
/envelope

**Comment by digiltd** [comment]
It does look possible, but it doesn't look easy, especially if you don't know much about this sort of stuff.

https://community.smartthings.com/t/smartthings-control-of-lg-webos-3-0-tvs/75302/16

The results are also not really worth it, I did the same to my Samsung but the whole concept was massively flawed because the TV had to be on in order to receive a signal. So if you turned it off, you could not turn it back on again using the network.

You are better off getting a Harmony Hub

**Comment by crsnwby** [comment]
I see that does look a bit too much work for not moving my arm 3 inches to pick up the remote. I wondered as the android app anymote works without a hub so assumed/hoped there were HTTP commands I could just use in ha-bridge.

**Comment by digiltd** [comment]
Oh, well that is something different, I am pretty sure I have heard of others using Anymote, so I think it is possible. In that instance the Android device is the hub. Looks like you can also use Alexa with Anymote directly.

**Comment by crsnwby** [comment]
Yea but didn't want to use anymore as it's a pain and another app to keep running. Was hoping to just add commands to ha bridge

**Comment by masterchop** [comment]
Yes, you can there is an option to execute command line commands. you can just do like:

`python scriptname.py <parameters>` that works for me. i was using python and bash

**Comment by crsnwby** [comment]
Do you have a working example? not sure how to set it up using python.
