### ISSUE TITLE
Possible for a simplified Mobile interface?

### ISSUE THREAD

**Issue by danmed** [bwssytems/ha-bridge#688]
Would there be any scope to have a simplified mobile interface with just the name of the device and the on / off / dim options?

I have all of my devices through HA-BRIDGE and that's the one thing i am missing is a simple interface to just control them when the Echo is being difficult or my internet is out..

**Comment by bwssytems** [comment]
Was not planning on it. You could use the myriad of apps that control hue lighting to do the same.

**Comment by tuicemen** [comment]
I've been toying with creating an Android interface simular to a Windows PC interface I created. (Alex10)
However limit it to just have the options your looking for.
Sadly I doubt I'll get at that till fall .

**Comment by tuicemen** [comment]
I'm not sure this is needed anymore with the ability to turn on/off from the Alexa App now added.

**Comment by audiofreak9** [comment]
I've been hoping for one as well, wrote my own in fact, but now I have to agree with @tuicemen, not needed now that the Alexa app has control.

**Comment by audiofreak9** [comment]
@tuicemen 
I've even written my own Alexa Skill that gives me the ability to query the status (on/off/dim level) of all my ha-bridge devices by voice.  I also have a Raspberry Pi that monitors my pool and hot tub that I can query with the same skill, and I threw in a weather query that is short and to the point for good measure, rather than Alexa's typically long winded weather report.  

@bwssytems 
I have really enjoyed using the ha-bridge and seeing it grow over time, thanks for all your support!

**Comment by tuicemen** [comment]
@audiofreak9  the skills sounds real cool,
I know lots of x10 users that would love that.

**Comment by bwssytems** [comment]
@danmed Has any of the mobile apps helped you out on this?

**Comment by bwssytems** [comment]
Since this is an old request and it will not be implemented.
