### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by emiliosic** [bwssytems/ha-bridge#69]
Could you please update the documentation on the following?
After upgrading to 1.4.1d, added a new Vera device and on Bridge Devices, the ID column is empty, and tests fail.
On already existing devices that are already created, there is an ID. When editing those, after saving it, the 'Target' becomes 'encapsulated' instead of default. What does this mean?
Also, thanks for adding a 'Dim' URL. The increasing an on/off switch; this field is populated. Is it now required? Other existing devices are empty.
I did populate it on a dimming Vera device and works; but I'm not sure if it's required of Echo or Harmony.

**Comment by bwssytems** [comment]
This is a test version, there maybe bugs in it and seems you have found a bug.
The support team
On Mar 18, 2016 6:56 PM, Emilio Panighetti <notifications@github.com> wrote:Could you please update the documentation on the following?
After upgrading to 1.4.1d, added a new Vera device and on Bridge Devices, the ID column is empty, and tests fail.
On already existing devices that are already created, there is an ID. When editing those, after saving it, the 'Target' becomes 'encapsulated' instead of default. What does this mean?
Also, thanks for adding a 'Dim' URL. The increasing an on/off switch; this field is populated. Is it now required? Other existing devices are empty.
I did populate it on a dimming Vera device and works; but I'm not sure if it's required of Echo or Harmony.

**Comment by emiliosic** [comment]
As for the entries without an ID, found out the hard way that it's not possible to alter these entries, so end up recreating the database (several times).
What I found is that once an entry moves from the list of available options to the table containing existing entries, immediately adding another entry can cause this issue.
What I end up doing is refreshing the browser every time to the ng front-end reloads. Happened using Chrome (and I didn't find it stable under Safari either).
BTW: Once I recreated the database; didn't run into 'encapsulated' entries, so that might have to do with schema changes?

**Comment by bwssytems** [comment]
So, you do not use the vera utilities to add devices? I see this happens on the Manual Add only. So that is a bug. As far as the url's, they are not required in any combination.

**Comment by emiliosic** [comment]
This happens when adding devices and scenes from the Vera devices and scenes menus, not manually. The first works fine; then ads another one without refreshing the browser and run into this issue.

**Comment by audiofreak9** [comment]
I can report the same problem with the Harmony devices and scenes.

**Comment by bwssytems** [comment]
I have found the issue and it will be fixed
