### ISSUE TITLE
Not an issue, a community query

### ISSUE THREAD

**Issue by Andyjd86** [bwssytems/ha-bridge#708]
As the title suggests this isn't an issue, but I couldn't think of anywhere else to put this. I have used the HA-Bridge for a while now to control some milights. It works pretty well although I don't use it to an advanced level. I regularly follow the issues here to see if anything useful for my setup is mentioned, and it occurred to me that a forum or blog would be really useful to interact with other users who use HA-Bridge.

There are a number of things that I would like to know how to do or have instructions on how to get a specific configuration working, but raising it as an issue doesn't seem appropriate. Is there already a community out there where this could be integrated, or is it something that other people would find useful to set up?

Thanks for creating HA-Bridge.

**Comment by FloFoer** [comment]
Of course there is something on reddit like [/r/homeautomation](www.reddit.com/r/homeautomation) but this is in a very much broader sense than just ha-bridge.  

I agree with you that a plattform to ask questions or to show off what you've accomplished (and how you did it) to inspire or instruct others would be nice.  

We could of course just create our own subreddit, something like /r/habridge.   
But i don't know if we are enough (active) people for something like that to be more than a self talk.  

@bwssytems What's your opinion about that?

**Comment by digiltd** [comment]
@Andyjd86 It is true that a "question" is not technically an "issue" and some repos are stricter than others about this. I think this repo is less strict about it (@bwssytems correct me if I am wrong). Questions tend to get answered rather than closed immediately if they are not actually an issue, and other users help provide answers. 

> There are a number of things that I would like to know how to do or have instructions on how to get a specific configuration working

Have a browse of the issues (open and closed) though a search is probably better if you know what you are trying to do 😄 . 

I like the idea of users creating wiki pages with their tips and instructions etc. I did this after I finally got ha-bridge working Kodi as I thought it covered some concepts can be applied to other things.

Regarding inspiration in general... there are loads of communities out there that appear to focus on a specific home automation platform. I use openHAB for my home automation stuff which has a very busy community, but browse the forums of the others because the concepts are usually very similar, and people like to chat anything and it might surprise you what you stumble upon or what triggers an idea for you try yourself.

Good luck 

https://community.openhab.org/

https://www.domoticz.com/forum/
https://forums.homeseer.com/
http://lightwaverfcommunity.org.uk/forum/
https://community.home-assistant.io/

https://www.reddit.com/r/amazonecho/
https://www.reddit.com/r/homeautomation/
https://www.reddit.com/r/Hue/

**Comment by tuicemen** [comment]
Besides the links digiltd provided do a search on Google for homeautomation forums. 
There are a few old long running forums with lots of Ideas posted.
Many also have threads containing discussion on the HA-Bridge, a search on the forums will display them.

**Comment by bwssytems** [comment]
The wiki on this github page is editable and can have additions.
