### ISSUE TITLE
Delaying a Script or URL execution

### ISSUE THREAD

**Issue by vinochino** [bwssytems/ha-bridge#714]
Hi there,

I tried to figure this out for the whole day now but I can't get behind, what might be the problem. 
The URL invoke for Power off won't get delayed if I configure the delay to 10000ms or anything else.

Under Edit/copy my device ->Off item, I configured a script as first entry and put my delay to said 10000ms. The second entry is a URL device and I put the same delay here for testing. But nothing gets delayed at all.
I also tried to check my device.db but couldn't find the device I was looking for. 2 devices are listed, but I got 5 overall in the HaBridge configured. And all of them are working. The 2 devices which are listed were scripts i don't even use anymore and are also not in my bridge devices anymore, if that is of any interest.

The idea was to shutdown Kodi over a script, which already works by its own. And then power off the Sonoff wifi switch a bit later so that Kodi will be clean shutdown. All with one Alexa command.

Thanks for any help

**Comment by FloFoer** [comment]
One thing that irritated me at first because my delays didn't work: The specified delay is applied after the item execution instead of before, so it's the delay until the next item and not the delay for the item itself. Maybe that's your problem too. 

This seems unintuitive to me, i thought at first the delay is for the item itself, but no.

**Comment by vinochino** [comment]
Yes I read that today too. I agree that this is unintuitive, but it should run now because I set the delay for both entries. I did that because the actual delay on the first entry didn't work either. I took a screenshot to show you my device settings. Thanks.
![unbenannt](https://user-images.githubusercontent.com/25873638/28786615-fe1d08cc-7619-11e7-8db2-bab836b238df.PNG)

**Comment by FloFoer** [comment]
If your device.db doesn't contain your devices there are two possible reasons:  
a) You're looking at the wrong device.db, maybe check your db location settings.  
b) One of your configured devices somehow is invalid and thereby the repositoryWriter fails to save your db. In that case your devices would be gone after a restart.   
Reason a) is more likely because with b) execution of the invalid device would surely fail and you said they all work.  

Your items get both correctly executed but with no delay? Interesting.
Delays work for me on 4.5.6, if you're not on the newest version i would give it a try.  
Otherwise switch on debug mode and look at your log for anything unusual, because i can't find anything unusual in your screenshot.

**Comment by vinochino** [comment]
Wow indeed, I updated to 4.5.6 from 4.5.5 and it seems to be working now =) Thanks for that advise FloFoer.
But I'm still wondering what device.db it could be using, although my initial problem is now solved. 
![unbenannt](https://user-images.githubusercontent.com/25873638/28788516-5a9e8056-7621-11e7-9488-7d9f8d57bc28.PNG)

**Comment by FloFoer** [comment]
If you configure it that way your device.db is under /data/device.db because the execution folder seems to be root for me. I would set the device.db to the same folder as your habridge.config above for it to be in the data folder in the habridge folder instead of data unter root.

**Comment by vinochino** [comment]
Thanks a ton. I never changed the initial config of the device.db but you were absolutely right.
Solved in all concerns. Thanks again! 

Und schöne Grüße =)

**Comment by FloFoer** [comment]
Kein Ursache ;)

Since this is solved you as creator can close the issue by yourself (button next to comment button), it doesn't have to stay open if there is nothing more to do here (for bwssystems). I'm just a user too so i can't do it.
