### ISSUE TITLE
Toon does not see the HA-Bridge

### ISSUE THREAD

**Issue by mAiden88** [bwssytems/ha-bridge#720]
I've been trying to link HA-Bridge for a couple of days to Toon Thermostat.. I'm not lucky..
Toon comes everytime with "Can't find any Hue Bridge on you're network"
Hue apps see the HA-Bridge that is working well:

![screenshot_19](https://user-images.githubusercontent.com/30929666/29214506-ea1742e8-7ea7-11e7-8acf-e4dd10b2feb3.png)

But Toon dont see it.

I scan today my local network, could not find HA-Bridge in my network.

Official Hue Bridge can be linked to Toon.

Whats wrong?

**Comment by bwssytems** [comment]
Based on what I can find on the Hue Integration, it is using the cloud api for the HUE. The ha-bridge is not based on that api as it is philips own cloud. So, this will not work in this fashion.

**Comment by shadi1989** [comment]
@bwssytems I got 1 Toon working the way @mAiden88 is trying to explain, also got 1 Toon who isn't working. Guess that the issue is somewhere in the Toon rather then in the HA-bridge.
Is it possible to gain access to the archived versions of HA-bridge? I got 4.5.5 running while 4.5.6 is the latest version.

**Comment by mAiden88** [comment]
All versions can be found here:

https://github.com/bwssytems/ha-bridge/releases

Try also 4.5.5 version, with no luck :(
