### ISSUE TITLE
Phillips Hue with Ikea TRÅDFRI 

### ISSUE THREAD

**Issue by thomasj2710** [bwssytems/ha-bridge#727]
I've just purchased google home along with chromecast and chromecast audio. After doing some research, I'd like the usability and connectivity of the hue bridge alongside a few colour changing bulbs, but the cheap price range of ikea bulbs to pair to the Phillips range. Is there anyway to do this? Will I need the starter kit for both types of smart bulbs?

**Comment by bwssytems** [comment]
You will need a Philips Hue Bridge to do this. ha-bridge does not talk to Hue or Tradri bulbs directly.

**Comment by thomasj2710** [comment]
@bwssystems So a Philips Hue bridge will be able to connect to TRÅDFRI bulbs, providing I have both bridges in my house?

**Comment by FloFoer** [comment]
Since recently the tradfri bulbs can be used with the hue bridge. That is because both hue and tradfri bulbs use the same protocol. Theoretically you don't even need the tradfri bridge. However, in order for this to work the tradfri bulbs must have the newest firmware. The ones you can currently buy likely don't have it (yet). The firmware update only works via the tradfri bridge. So you will need the tradfri bridge at least to update the bulbs. After that you don't need it anymore and you can use them with the hue bridge alone.
