### ISSUE TITLE
Setting HUE brightness from within item

### ISSUE THREAD

**Issue by leyton01** [bwssytems/ha-bridge#738]
I am wondering where I need to put the parameters to set a hue bulbs brightness when I call it as part of a device?

In my "On items" I have "Hue device" and it has auto-populated Target Item {"ipAddress":"192.168.0.43","deviceId":"1","hueName":"MyHue"}

I think I need to pass "state":{"on":true,"bri":254} to set it to full brightness but I am not sure where to put this?  I have tried as part of the target item field but no luck.

**Comment by leyton01** [comment]
Just to explain what I am trying to do here -

I have a "scene" (bedtime) which when I turn on via Alexa it turns off the aircon (harmony device), turns off the TV (harmony activity) and set the lights to 5% via a Vera scene.

I am getting rid of the Vera as I have bought a Fibaro HC2, as there is no support yet for the HC2 I thought I might be able to set the brightness from within the multi-command itself.  I suspect I am not doing this correctly as it is technically a passthru and does not actually call a command?

**Comment by FloFoer** [comment]
As you have already realized it's a passthru. If you want to set the brightness with a passthru device you would have to say something like "alexa, set light to 5%". 
If you have a "faked scene" set up as a normal device and if you want to set the brightness of a hue bulb during the "on" command for this scene you would have to manually call the hue bridge api.  
This means adding a HTTP item to the onUrl with target like http://[hue-bridge-ip]/api/[username]/light/[l            ight-id]/state using http method POST and the correct json values in the http body.   
I'm not at home right know so i can't go into more detail because i don't remember exactly how the GUI looks :D

**Comment by leyton01** [comment]
I thought this might be my problem and I look forward to your example - I couldn't figure it out from the readme or FAQs earlier.

**Comment by FloFoer** [comment]
This would be an example (in json):
`{"item":"http://192.168.0.32/api/[username]/lights/1/state","type":"httpDevice","httpVerb":"PUT","httpBody":"{\"on\":true,\"bri\":50}","contentType":"application/json"},`  

So as i said, but with PUT instead of POST. 
In the onUrl:
1. Add a HTTP Device
2. Target item is:  http://[hue-bridge-ip]/api/[username]/lights/[light-id]/state 
If you don't know how to get a valid user for your hue bridge do this [very quick but informative getting started](https://www.developers.meethue.com/documentation/getting-started). The light-id is the value in the "ID" column in the bridge devices list. (Alternatively you could do a HTTP GET on http://[hue-bridge-ip]/api/[username]/lights to get a list of your devices incl. infos)
3. Http verb PUT
4. Http Body is {"on":true, "bri":50}. Replace 50 with whatever brightness you want between 1-254.
5. Content type is application/json

**Comment by leyton01** [comment]
I finally had some time to try your walkthru and it worked perfectly - thank you.
I now have a scene which controls some other devices and the lights directly.

Perhaps direct control of lights could be added in the future rather than passthru as all of this information (username, hue light IDs) is already captured by HA Bridge and could be nicely integrated into a simple UI.

**Comment by bwssytems** [comment]
Unfortunately, the ha-bridge does not talk to hue bulbs directly, that is the reason for the pass thru. Glad it is working for you.
