### ISSUE TITLE
Error on calling url to change device state

### ISSUE THREAD

**Issue by Fabi1309** [bwssytems/ha-bridge#743]
Hey guys,

I setup my HA bridge and tried to use it with FHEM. 
I created a web instance and an url to turn my tv on and off:

http://xxx.xxx.xxx.xx:xxxx/fhem?cmd=%7Bsystem("irsend%20SEND_ONCE%20TV%20KEY_POWER")%7D

Even tho I changed the { }into %7B and %7D, it is still not working and I get: 

Request Error, Pleae look in your habridge log: error {"type":"6","address":"/lights/1","description":"Error on calling url to change device state","method_name":"/lights/1state"}

Do I have to enter anything in MapID to make it work? I left it blank.

I hope I can fix my issue with your help!!

Greetings 
Fabi1309

**Comment by tuicemen** [comment]
you should not need to enter any thing in the map ID.
since this is a simple http call and if your call works from entering it directly into a browser then
your on item should be:
Type: HTTP device
Target item: 
http://xxx.xxx.xxx.xx:xxxx/fhem?cmd=%7Bsystem("irsend%20SEND_ONCE%20TV%20KEY_POWER")%7D
content type: text/html

**Comment by Danscho** [comment]
Fhem has a new security feature to prevent CSRF attacks.
Did you disable the csrf token generation?

I took the approach the create a new API, disable the csrf token creation and since my habridge is running on the same pi i limited access to 127.0.0.1 only.

More info here: https://wiki.fhem.de/wiki/CsrfToken-HowTo
