### ISSUE TITLE
Harmony hub not working

### ISSUE THREAD

**Issue by cherowley** [bwssytems/ha-bridge#751]
Noticed that the harmony hub stopped working in the last week or two.
Was on version 4.2 now on latest 4.5.6 still the same..

None of the activities are showing up in the harmony activities screen?
Or devices..

Any ideas? Saw something in the readme about building a module? Never did that before and can't see what to do in the readme or wiki.

Up until the last week or two its been working fine and untouched for many months...

**Comment by FloFoer** [comment]
Works for me. (with the normal jar and without having to do/build anything extra) 
Do you have your Harmony Hub correctly set up in Bridge Control -> "Harmony Names and IP Addresses" ? Has you Hub a static IP? If not maybe it changed since then.  
Does your Hub itself still work without HA-Bridge? (Does it work with the smartphone app?) Mine sometimes freezes and doesn't react to anything.  
Maybe try restarting the Hub and HA-Bridge. I would recommend to look at the HA-Bridge log during HA-Bridge startup to look for something signalizing a malfunction regarding the connection to the Hub.

**Comment by cherowley** [comment]
Oh bloomin eck, looks like it was some wrong routing tables in some of my switches, had to reboot the switches, not had that before!
