### ISSUE TITLE
Controlling groups of Hue bulbs

### ISSUE THREAD

**Issue by spud** [bwssytems/ha-bridge#756]
I have two individual Hue bulbs above the couch. In the Philips Hue app, I can put them into a "Couch Lights" group, and control them together as a unit.

How do I create the same capability with the bridge? I'd like to be able to say "Alexa, turn on couch lights", "Alexa, dim couch lights," etc. 

What's the best way to accomplish this?

**Comment by FloFoer** [comment]
Of course you could just create a device as some sort of "scene" and put actions for all devices in it. 
Alternatively (and better i think), if you use the [current release candidate for V5](https://github.com/bwssytems/ha-bridge/issues/735) you can actually create groups with the hue app if you connect it to HA-Bridge just like with a real hue bridge. Only thing you must do for it to work is to uncheck "Add default scenes" every time before saving the room (important! - HA-Bridge can't handle real hue scenes) 
Currently the HA-Bridge Web UI doesn't let you manipulate your groups. 
You can read more about how i implemented the rooms and what to know about it [here](https://github.com/bwssytems/ha-bridge/issues/713) 

Also, regarding Alexa: The echo discovers groups via the skill, not built-in like with the lights. Which means, the traditional hue implementation for groups doesn't work with Alexa and HA-Bridge, however there is a workaround for this: The group gets presented to the Echo as another fake light bulb, like all the other HA-Bridge devices. For that to work you must manually enable this feature for every room by adding "exposeAsLight":"192.168.0.30" to the room in the group.db file (restart ha-bridge afterwards). Use the ip-address of your Echo. No need to do that for other devices than for an Echo, because these can handle rooms directly. The manual edit is necessary because group management is not implemented in the Web UI.

**Comment by bwssytems** [comment]
Any update on this?
