### ISSUE TITLE
Change How HA-Bridge emulates devices

### ISSUE THREAD

**Issue by lonebaggie** [bwssytems/ha-bridge#767]
I Have set all my Devices within HA-Bridge , which has been faultless in operation.  I use Domoticz  to manipulate  these devices via the Hue interface . Again this works without issue . Is it possible to change what HA-Bridge advertises what these devices are ? 

Domoticz  believes all the devices advertised by HA-Bridge are RGBW Dimmers. I can not change the  dimmer type in Domoticz so my White LIghtwaverf Dimmers are  interpreted as Colour dimmers. Is this a Domoticz issue ?

**Comment by FloFoer** [comment]
You could use the current [release candidate v5](https://github.com/bwssytems/ha-bridge/issues/735). v5 has better color support and also automatically distinguishes between "Extended Color Lights" and "Dimmable Lights".  
Instead of using Extended Color Light for all HA-Bridge devices it decides what it is for each device via these rules: 
1. If it's  Philips Hue passthru device it takes the info from the real hue hub.
2. If it's no passthru it's a dimmable light if it has no color command items, otherwise it's a Color Light. The color command items are new in this version and they get executed if you send a color change request to the HA-Bridge device via the app or something similar.

**Comment by lonebaggie** [comment]
Tested with ha-bridge-5.0.0rc2.jar works much better with Domoticz reports correct switches  . Beta too unstable to use, errors with put commands  . Will wait until stable many thanks for the heads up

**Comment by bwssytems** [comment]
Please report beta rc 5 issues on the rc thread. Thanks
