### ISSUE TITLE
Sonoff

### ISSUE THREAD

**Issue by Madhaus01** [bwssytems/ha-bridge#771]
Is it planned to integrate Sonoff products in the future?
greetings Mad

**Comment by tuicemen** [comment]
I've been controlling Sonoff devices with HA-Bridge for over a year now.
This was done by flashing the sonoff module with a thirdparty firmware.
Since itead refuses to release its protocol the Bridge can't send command until someone sniffs out what the ewelink app is sending.
Now with an Alexa skill available for these the bridge isn't required to interface these with Alexa.
