### ISSUE TITLE
Issue: push button to pair HABridge

### ISSUE THREAD

**Issue by kasperleralf** [bwssytems/ha-bridge#778]
Hello,
I'm running the actual jar 4.5.6 on a Windows 10 machine in Administrator-Shell.
I tried to connect with alexa and harmony both, but I'm always asked to pair the HABridge. Discovery of the HABridge works well. What am I doing wrong. HABridge is running on port 80, UPnP is activated in the router.

Regards,
Ralf

**Comment by michaelhinchey** [comment]
Try a different port like 8080 or 8081

**Comment by kasperleralf** [comment]
Thx. I tried that already. Same effect. Switched especially to port 80 since this is recommended for Alexa ans others

**Comment by michaelhinchey** [comment]
I noticed today that when I had Localhost written instead of my actual ip address, vera didn't see my devices. under bridge control and in the space for UPNP IP Address.  I don't know if I just made a quick assumption but when Local host was in there Alexa couldn't see them.  Worth a shot.
I dont know if these are necessary but Also make sure they are both on same network and you can ping both. 
The jar seems to be running because you are able to open the bridge locally right?

**Comment by kasperleralf** [comment]
Thx. Yes, I CAN Open the habridge Website locally. Binding is on an explicit IP-Adress

**Comment by michaelhinchey** [comment]
OK.  Sorry I couldn't help.  I never tried port 80 buy I'll assume it would
work just as well. If you have anything under those ports you wouldn't of
been able to reach the bridue I assume.









    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by michaelhinchey** [comment]
Wait.
  What hub are u using for the connections?  Vera, smart home ,?









    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by kasperleralf** [comment]
As hub I Tried: Alexa, innogy smarthome, yonomi and Logitech Hub. Evelyn time the same, that they Want the Button pushed

**Comment by audiofreak9** [comment]
Do you also have a REAL Hue Bridge on the network?  If so turn it off while discovering ha-bridge.

**Comment by kasperleralf** [comment]
No. I don‘t have a real hue bridge

**Comment by audiofreak9** [comment]
On the Bridge Control page, click the "Update Security Settings" button.  There is a "Use Link Button" checkbox, set to true, then click Update and try discovery again.

**Comment by kasperleralf** [comment]
Thx. No effect. Habridge isn‘t recognised

**Comment by michaelhinchey** [comment]
Have you ttied a different machine?
Turning off all firewalls and antiviruses?










    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by bwssytems** [comment]
Ok, when you activate the use link button feature. The main page will now have a button. "Link Button" that you need to press when being asked by the other system.

**Comment by kasperleralf** [comment]
Thx. Works now for the Hue-Native-App and for Alexa. Still having the same issue with the innogy-SmartHome-App. It doesn‘t recognise ha-bridge as Hue-Bridge, even when I enter the IP-Adress manually.

**Comment by bwssytems** [comment]
Unfortunately, YMMV with different apps. Some apps check to see of all features area available and the ha-bridge does not have them all.

**Comment by kasperleralf** [comment]
Ok. Do you have a list, which features aren‘t implemented to cross Check with innogy? Especially since the original hue app doesn‘t have this problem

**Comment by bwssytems** [comment]
I don't have that list and probably won't. Also, does the innogy want you to login to accoutns.meethue.com? If it does, it will not work with the ha-bridge.

**Comment by kasperleralf** [comment]
Ok. No, I don‘t have to Login to the meethue-account.

**Comment by bwssytems** [comment]
Then something you could debug with the traceupnp if you need it to work.

**Comment by kasperleralf** [comment]
![4fb32fdb-8183-45eb-9c64-538c5731e901](https://user-images.githubusercontent.com/33398817/32522181-9a70faae-c416-11e7-8c40-01744ac7b595.jpeg)
.

**Comment by kasperleralf** [comment]
![1eee7aeb-e1ea-40b9-8a38-062097b6e61c](https://user-images.githubusercontent.com/33398817/32522346-3dab1074-c417-11e7-9513-06d300e89707.jpeg)

**Comment by bwssytems** [comment]
That is not enough as those are generated messages generated by the bridge on a timer. I need the whole log from the output of the ha-bridge.

**Comment by bwssytems** [comment]
IS there any progress on this?

**Comment by kasperleralf** [comment]
Hi,
innogy Hotline has no idea :-)
I checked the logs, but there is no entry in debug-mode visible, which has the IP-Adresse of the innogy smarthome Basestation.

**Comment by bwssytems** [comment]
So, did you get the Echo connected that you had issues with?

**Comment by kasperleralf** [comment]
Echo works fine now. Only the innogy smarthome won‘t recognise the HA-Bridge

**Comment by bwssytems** [comment]
Do they use the account.meethue.com method, which will not work with ha-bridge since it is not a Philips product? Otherwise, if you are not seeing the ip address of your innogy come through in the log when trace upnp is on, it does not use the upnp method and uses the Philips cloud method.

**Comment by kasperleralf** [comment]
Hm, seems to be the only explanation. I wonder that I don‘t have to enter any login-Data for meethue.

**Comment by audiofreak9** [comment]
According to [this inology forum post](https://community.innogy.com/frage-ansehen/wie-funktioniert-das-einbinden-von-philips-hue):

"You have to click on a new device, then click on select device, then on lights, then click on Philips Hue.

First, the center will install a driver for Philips Hue, when that is complete, you can select or install the Philips Hue lamps.

Of course you also need a Philips Hue Bridge. It does not matter if you take the new or old Philips Hue Bridge."

**Comment by kasperleralf** [comment]
Yes, I did it exactly like that. Driver is installed
