### ISSUE TITLE
Allow custom hue-bridgeid?

### ISSUE THREAD

**Issue by petewill** [bwssytems/ha-bridge#779]
I am trying to move my bridge working with Google Home to a new computer (a low power Raspberry Pi).  Because I can no longer set up the bridge with Google Home (dang you Google!!) I was hoping I could somehow transfer the config to the new computer.  I have successfully moved the config and database files and I'm able to control my Vera devices on the Pi.  Unfortunately my Google Home does not see the bridge.  I am guessing this is related to the hue-bridgeid (and perhaps some other unique identifiers).  Is there any way to add those to the Bridge Settings so I can use a new computer with my already configured bridge?

**Comment by FloFoer** [comment]
From what i've heard here i don't think that the problem with the Google Home and HA-Bridge will go away if you run HA-Bridge on another computer. 

If you mean the "ID" in the Hue App under Settings -> Hue bridges -> info, this is calculated based on the MAC address of your computer, so it changes automatically if you run it on a new computer. 
If you mean the name that is also displayed there on the screen (default "Philips Hue"), this is fixed in code. You could change that in the file HueMulator.java in the methods getConfig() and getFullState() by replacing the String "Philips Hue" in the createConfig() and new HueApiResponse() calls with whatever you like. I called it "HA-Bridge" to distinguish it from my real Hue Bridge in the App.

**Comment by wendy2702** [comment]
@FloFoer can you please specify the file location of the file: "file HueMulator.java"?

Can't find it after unpacking the ha-bridge jar file.

Thanks

**Comment by petewill** [comment]
@FloFoer Yes, I am referring to the ID that is calculated by the MAC address.  I realize that it is currently automatically generated by the MAC address but I was hoping to have an option to override that.  Basically what I'm hoping to achieve is to take my working bridge on onecomputer and move it to my new (low power) computer.  I am not positive but I think that my Google Home is looking for the "hue-bridgeid" when trying to connect which is why I can't get things to work on my new computer.  It also could be some other setting like the "USN: uuid" as that also seems to contain the MAC address.

**Comment by bwssytems** [comment]
So this would be another field to put in the bridge control page. Looks like an enhancement.

**Comment by michaelhinchey** [comment]
Damn I didn't know you could move the bridge to a new computer.  I kind of
did it like this but had to change the port number.  So I built my htpc
finally and I was hesitant to move it because I didn't want to put in
another different port.  Could you kindly explain how to move it.?
   I moved it like this,
   Saved my configuration files,  then logged in from a different computer
that I wanted the new bridge on. I then changed the ip address after
running g the ha bridge java file on the new computer.  It wouldn't take so
I changed the port and it worked. I don't think I needed to upload the cfg
file that I previously saved.
   There has to be an easier way though.








    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by petewill** [comment]
@bwssytems Yes, sorry, I didn't know how to classify it as an enhancement.

@michaelhinchey That's pretty much what I did.  I just copied the files from my old computer into the same data folder on the new computer.  Because the IP address changed I manually changed that in the habridge.config file using NotePad++.  This didn't fully work though because my Google Home would need to be able to find a new bridge which it's not able to do.

**Comment by michaelhinchey** [comment]
@petewill Where are the files on a computer stored?  I would like to either change the ip address since the bridge will not run on a computer that i built for some reason. I changed the ip address of the bridge from a working computer to another computer on my network and it will not run on that computer.   I need to get it back on the other computer and figure out why it wont run on my new built PC (It actually ran a few times and then it disappeared and will no longer run on it now).

**Comment by petewill** [comment]
@michaelhinchey the files were stored in the data folder where the jar file resides if I remember correctly.  I don't have access to a computer to confirm though.  The main problem though is the MAC address is part of the ID so I'm not sure if changing the IP will help (unless you're talking about your Vera IP).  You should be able to use the config file so you don't have to add all the devices again but I'm not positive.

**Comment by michaelhinchey** [comment]
@petewill  O man  That helped tremendously.  I always wondered where the configuration was getting saved.  NOW I KNOW!  I was able to move those data files to another folder just in case I needed them and the bridge came right bac up on the computer I needed it on(The new one) Besides a good cup of JOE i made this is an Awesome start to my morning 👍 
 BTW  I am sorry for hijacking this thread.

**Comment by bwssytems** [comment]
@michaelhinchey Please close the other thread you opened for this as well.

**Comment by michaelhinchey** [comment]
@bwsystems 
I will as soon as my error's go away.  I will update the other thread with my errors. 
Bridge will not talk to vera anymore still.  I cannot turn on/off any of the devices.

**Comment by petewill** [comment]
@bwssytems Thank you so much!! Your addition is working great for me.  It is so nice to have this running on my Pi instead of a full computer.  Thanks again!
