### ISSUE TITLE
Color setting issues

### ISSUE THREAD

**Issue by Abrax16** [bwssytems/ha-bridge#799]
Hi everyone,

I'm just about to configure my ha bridge and got a little trouble with the new color functionality since it's not really documented so far.

Either way I already figured out some on my own but got a lot of trouble with my color settings.
I found some hints on rgb-format transformation but didn't really know how to implement it into the call-config on my ha bridge.

My only problem is that my controller doesn't accept rgb values directly. It wants a hex number between 00 to FE (0 to 255) to determine the requested color.

I found 00 to be pure blue, 55 to be pure green and AA to be pure red. And FE is nearly perfect blue.
So it's basically a color circle. But I can't figure out how to get this into my bridge device config.

I assume it has to be something like:
udp://XXX.XXX.XXX.XXX:8899/0x40${color.math("this is where I'm lost").hex}

I could imagine a script to determine the needed code but it would need the rgb-values as input.

Any help?

Best regards

**Comment by bwssytems** [comment]
Sorry that I forgot to put the color attributes in the doc, will update that soon. As far as a conversion to that color wheel, you'll need to search for that on the web.

**Comment by Dud3z** [comment]
Same Thing here.

**Comment by FloFoer** [comment]
This sounds like milight/limitlessled to me, am i correct? 
If yes, this is already implemented. (for the v5 milight/limitlessled api) 

The usage for that is as follows: udp://ip:port/0x${color.milight:x} where x is a number between 0 and 4 (0 all groups, 1-4 specific group). The group is neccessary in case the color turns out to be white (white is handled a little bit different than normal colors in the milight api). The correct group on must of course be sent before that udp packet, like always.  

So if you want a color change for example for group 2 you would have two items in the colorUrl ("Color Items"): 
The corresponding group on: udp://192.168.0.35:8899/0x470055 
The color change for this group: udp://192.168.0.35:8899/0x${color.milight:2} 

Or for all groups: 
The corresponding group on: udp://192.168.0.35:8899/0x420055 
The color change for this group: udp://192.168.0.35:8899/0x${color.milight:0} 


Side note: Because of the limited colors with milight (only 255) setting the temperature via the hue app doesn't result in anything useful with milight. So i would stick to the color tab.

**Comment by Abrax16** [comment]
Nailed it.

The config is done, but problems aren't solved yet.
There's no testing for the color-management on the ha-bridge website, am I right?

Furthermore Alexa pretends that my device doesn't support color feature...

How to get that working?
I got no hue bridge so I can't activate the hue skill, is that necessary?

Best regards

**Comment by FloFoer** [comment]
Yes there is currently no testing for color on the ha-bridge website, you could use a hue smartphone app instead. 

Regarding Alexa, yes, sadly this won't work. I quote myself from the v5 testing issue: 

> This is due to the fact that alexa does on/off/dim natively & local, but color works through the official hue skill. Since HA-Bridge is not linked to a hue account you can't link ha-bridge with the hue skill and thereby color commands aren't possible without programming a custom skill for alexa and exposing ha-bridge or another server as middle man to the internet. I described this behavior and the rooms feature [here](https://github.com/bwssytems/ha-bridge/issues/713)
I still implemented this because it's nice to have color at least via apps.
The only way at the moment to get anything like a color command with alexa is to create a device for each color. I did that for my milight ambient light. For example i created a device "Ambient blue" which is a stateless device which when i say "ambient blue on" changes the color and also sets the correct status for my main "Ambient" device, so that it's displayed correctly in my hue app. I also applied an ip filter to these color devices so that they are only visible to alexa and not in my hue app.

**Comment by Abrax16** [comment]
Well too bad. So at the moment only on/off/dim with Alexa.
But thank you very much for that detailed answers.

Is there something in development for adding these features to Alexa?

**Comment by FloFoer** [comment]
Got a statement from the hue developer support once: 

> "Alexa commands (e.g. on&off, dimming) are natively integrated into Echo device and users can issue commands out-of-box. For other advanced commands (e.g. changing colors and control scenes), users need to enable Alexa Hue skill for the commands to work."

Also [here](https://community.home-assistant.io/t/color-support-for-emulated-hue-bridge-with-alexa/15179/2) was talked about that it will not get implemented natively.  

So there is nothing in that direction (that i know of). 
The other possibility would be to build a custom skill to connect to HA-Bridge. Maybe someone is tinkering a skill for that or has one already, but this would require to make HA-Bridge accessible via the internet in some way which is flagged as not recommended in the readme because it's a security risk.

**Comment by Abrax16** [comment]
Hmmm I made some research meanwhile and found out that it is implemented in USA already and will be available in other countrys "soon". But it was an entry from April'17 so...

Anyway thanks for your support. 
Maybe I'll change my hardware layout to make it compatible.
