### ISSUE TITLE
Is there a way to somehow get color with Alexa?

### ISSUE THREAD

**Issue by martin52525** [bwssytems/ha-bridge#813]
Is there a way to get colored lamps working with alexa? I dont want to create several lamps for each color. Alexa just says that that lamp doesnt support color.

**Comment by FloFoer** [comment]
Not in a simple way. I quote myself from the v5 testing issue: 

> This is due to the fact that alexa does on/off/dim natively & local, but color works through the official hue skill. Since HA-Bridge is not linked to a hue account you can't link ha-bridge with the hue skill and thereby color commands aren't possible without programming a custom skill for alexa and exposing ha-bridge or another server as middle man to the internet. 
I still implemented this because it's nice to have color at least via apps.
The only way at the moment to get anything like a color command with alexa is to create a device for each color. I did that for my milight ambient light. For example i created a device "Ambient blue" which is a stateless device which when i say "ambient blue on" changes the color and also sets the correct status for my main "Ambient" device, so that it's displayed correctly in my hue app. I also applied an ip filter to these color devices so that they are only visible to alexa and not in my hue app.

You could of course develop your own custom alexa skill to send color commands to your devices, but this would also require to make HA-Bridge accessible via the internet in some way which is flagged as not recommended in the readme because it's a security risk.

**Comment by martin52525** [comment]
Thanks for the explanation. So color only works online. :( 
Thought of creating my skill, to get some other funktionality like controlling heaters and to get the outside and inside temps with my raspberry. 
Besides that I dont like exposing a https API to the web, never sure if its secure.
