### ISSUE TITLE
how to connect harmony hub

### ISSUE THREAD

**Issue by krobipd** [bwssytems/ha-bridge#818]
hello

iam new to ha-bridge. I would like to connect my harmony hub to the ha-bridge to control some Homematic devices.

but my problem is that my harmony app keeps telling me that I have to press the middle button on the hue bridge. so where do I press this button? or what do I need to do.

**Comment by simonstamm** [comment]
I have the same issue. In #218 @memojo and @klein0r pointed out, that it helps to discover first the non-existent "Hunter Douglas Powerview Hub" and then trying the Philips Hue again - but this doesn't work for me either. Maybe it works for you?

**Comment by bwssytems** [comment]
This is an issue already identified in #797

**Comment by gpion** [comment]
Hello I'm having the same question
Problem is that don't event understand the answers (what mean those references to a "Douglas Powerview Hub" and Hue Bridge since the request is about an *Harmony* Hub issue)
I've correctly declared my Harmony Hub IP address in "Bridge Control" page
The "Harmony devices tab" is still empty
I guess I've to initiate a pairing process pair but I've been unable to found where it's described in the documentation
