### ISSUE TITLE
Add ability to run shell scripts

### ISSUE THREAD

**Issue by nerddeluxe** [bwssytems/ha-bridge#85]
I would like the ability to run shell scripts so that when I say "Alexa, turn on/off ...." the bridge can be configured to run a shell script. What I am thinking of creating is a Wake On Lan script.

**Comment by mvau** [comment]
This feature would be amazing.  Currently I have to call a PHP script via Apache which in turn runs a shell script via exec.  This is required for WOL and ps4-waker or for light bulbs that require a sequence rather than a single UDP packet (i.e. dimming LimitlessLED).

I really appreciate the work you have put into ha-bridge - it is a great solution and works flawlessly.  Thank you very much!

**Comment by tambnguyen** [comment]
I actually just set this up today using the Raspberry Pi 3 and a LAMP server, the same way mvau has it set up. It's actually pretty awesome.

**Comment by bwssytems** [comment]
This is great! The features will be coming soon, even the multiple calls for the limitlessLED
