### ISSUE TITLE
First action takes some time to actually trigger

### ISSUE THREAD

**Issue by robontheweb** [bwssytems/ha-bridge#888]
I run HA bridge on my Synology (213j) and i am really pleased with the functionality. 
What i noticed though is that the first action that is performed after a period of inactivity takes 6 to 10 seconds to start. Potential follow up actions are much quicker (takes up about 1 second). After a few minutes of inactivity i notice the same behaviour again. The actions that i use are HTTP calls. I see the same behaviour when i test the action with the Test On / Test Off buttons.

Is there a (configurable) sleep timer that i am not aware off? As far as i can see my Synology is in active mode and configured to go to sleep after 4 hours of inactivity.

**Comment by bwssytems** [comment]
So, you are hitting memory cache issues on your Synology. Since these machines do not have alot of memory, anything that is not needed gets swapped out. When the bridge is called, it takes some time to swap it back in at the OS level. Either run less programs on the synology, or switch to a raspberry pi for running the bridge.

**Comment by bwssytems** [comment]
included in the community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-first-action-takes-some-time-to-actually-trigger
