### ISSUE TITLE
Insteon Hub + Amazon Alex + HA Bridge (pi)

### ISSUE THREAD

**Issue by forumware** [bwssytems/ha-bridge#893]
Hi, 

Looking for some help, i currently control my hue using the amazon alexa. Also can control the insteon dimmers using the ios/android app or by using curl commands such as: 

For On: 
http://admin:password1!)@192.168.5.100:25105/3?02621DB5EC0F11FF=I=3

For Off: 
http://admin:password1!)@192.168.5.100:25105/3?02621DB5EC0F1300=I=3

How do i add this to the device area? I selected HTTP device and then http://admin:password1!)@192.168.5.100:25105/3?02621DB5EC0F11FF=I=3 in the target area... am i completely in the wrong are?

Thanks, 

FW

**Comment by forumware** [comment]
Ok i think i've figured it out on adding the devices, how do i get alexa to find them now?

**Comment by audiofreak9** [comment]
Do a device discovery.

**Comment by michaelhinchey** [comment]
There is plenty of info on this and is relatively simple if everything is
setup correctly.  Youtube or Google will guide you to this. Just do a
search on how to do a discovery of smart home on alexa.
  Make sure to download the alexa app from the playstore or iPhone store.









    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"
