### ISSUE TITLE
Relink Hue Account 

### ISSUE THREAD

**Issue by domier** [bwssytems/ha-bridge#900]
Apologies if this is a duplicate, I searched and nothing came up. 

As of this morning my Google Home is telling me I need to relink my hue account to edit, move, or execute commands, and that relinking my account will reset rooms assignments.

Has anyone else had this come up? 

I assume that since I don't have a hue account or a  hue Bridge this will break everything. Is there a workaround right now?

**Comment by Beerinder** [comment]
Same on my end.

**Comment by bwssytems** [comment]
I assume this is on an amazon echo? And if so, that is new.

**Comment by rafale77** [comment]
This is odd. I have not seen this yet. What country are you in?

**Comment by rjtrigo** [comment]
I used Google home and been asked to relink account. Now all my devices are gone and home app can't find ha-bridge. I'm from UK. Thanks

**Comment by 2relativ** [comment]
On Google home it could be a real problem because Google doesn't only work in your LAN. It is now necessary to link your hue-bridge to an hue account. Since the ha-bridge only emulates a hue-bridge there is no way at the moment to link to google home.

**Comment by bwssytems** [comment]
@domier Are you using a google home?

**Comment by bwssytems** [comment]
Google Home does not work anymore. See #764

**Comment by domier** [comment]
@bwssystems yes, I'm using a Google home. I've ignored its requests to relink, and so far things are still working. The constant reminders are a bit frustrating though.

**Comment by rjtrigo** [comment]
Hi Michael,
Were you able to link GH with hue again and make it work?

**Comment by Michael-D-Pine** [comment]
Yes, everything is working again as expected, I was pretty nervous about the account linking but in general it seems to be a pretty reliable mechanism, I haven't got anything set up but my Harmony is linked up and ready to be configured as well.

What happened was all the devices in Google Home were marked with a Red icon and when I clicked on one it said I need to relink my Hue account with a button to do so, the first it didn't work because I realised I was trying to sign in with my google credentials on a Hue account, did the same process signed in with Gmail and I was good to go.

Hope that helps.

**Comment by domier** [comment]
@michael-d-pine

Can you tell us a bit more about your setup? I'm a little hesitant because you say "everything is working again as expected", but you also say "I haven't got anything set up."

We're all concerned that the Google home can't be reconnected with ha bridge after updating the hue credentials, did you get that to work? I'm also not entirely clear how your harmony fits into the picture. 

Thanks!

**Comment by Michael-D-Pine** [comment]
That is because you didn't read my post properly or maybe just some different semantics, my nothing setup comment was in regards to the Harmony Hub and the fact it is link to my Google Home but I don't have anything configured on it yet.

In terms of the Phillips Hue bridge, it has relinked again and everything is working perfectly, however, I DID HAVE TO REASSIGN ALL THE LIGHTS INTO ROOMS AGAIN, I put that in capital on purpose to emphasis that everything is working ok but I did have to reassign the lights to the rooms.

All of my motion sensors and Hue setup is fine.

**Comment by domier** [comment]
@Michael-D-Pine 

Apologies, since everyone's setup is different I was having trouble filling the gaps in my understanding of yours.

How is your Phillips Hue Bridge connected to the Google Home?  Is it connected directly, or through the ha-bridge as an intermediary?  If it's connected directly we would expect it to work as google supports Phillips Hue bridges natively.

However, the understanding is that Google Home and HA-Bridge no longer can be paired, and therefore this question is about the connection between **HA-Bridge** and a Google Home, **not** about the connection between a **Phillips Hue Bridge** and a Google Home.

Were you able to successfully re-pair HA-Bridge with your Google Home after updating the Hue credentials in the Home app? 

Not trying to attack you, Just trying to understand before taking the plunge myself 👍

**Comment by Michael-D-Pine** [comment]
No it's all good, no attack taken :)

And I think it is good that we went down the clarification path my google search led me to this thread, I assume because it had "relink Hue Account" in the search term.

I have made the assumption a "ha bridge" was some tech term for Hue Bridge, so lucky you clarified first! :) I should not have assumed first and checked what a ha bridge was, so my apologies.

So yes my re-link was with a Native Phillips Hue bridge and NOT a ha-bridge.

Sorry to get your hopes up, hopefully you find someone else that might have been brave enough to do it before you :)

**Comment by domier** [comment]
Going to close this out.  Conclusion is that updates to the Hue pairing method have made it impossible to link ha-bridge to a home.  Existing setups will continue to work for now, but you will get an annoying reminder to update most times you execute a command.  Attempting to update the hue pairing will break the pairing with ha-bridge.
