### ISSUE TITLE
Echo Plus sending two commands

### ISSUE THREAD

**Issue by stbluesrul** [bwssytems/ha-bridge#943]
After the initial discovery of new devices the Echo Plus seems to issue commands twice to the bridge.  This only happens the very first time after a new device is discovered and I've only observed it on the Echo Plus (has built-in Zigbee radio).

For example, if I'm starting fresh with no devices on the Echo Plus and two are added during the discovery.  The first time I say "Alexa, turn on device 1." and "Alexa, turn on device 2."  The command will be sent from the Echo Plus to the bridge twice.  I've verified that these commands come from the Echo Plus using WireShark.  Also, if I add a third device after the initial discovery of the first two devices, the very first command for that third devices will get sent twice as well but not devices 1 and 2.  Has anyone else noticed this?

**Comment by nwang0** [comment]
Yes this happens to me as well. I managed to reproduce the issue reliably by asking "Alexa, turn off all lights". In the DEBUG log (root) I attached to the bottom, I can clearly see two calls to turn off the same light but with different user ids.

The problem is that two calls are made to harmony simultaneously and the second call get rejected by Harmony. In fact, when I set up a second light in the ha-bridge, it generates four calls, all later three get rejected.

This seems to be a Alexa echo problem, however it will be great if ha-bridge can implement a short term solution to bridge the gap.

Two suggestions:
1. Is it possible to synchronize the calls harmony across all http threads so the requests are handled one after another one?
2. A easier way may be limit the number of spark thread to 1. Will it work?

Request 1:
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,572 [qtp18195028-86] DEBUG com.bwssystems.HABridge.hue.HueMulator - HueMulator PUT called on api/* with request <<</api/uhWjJQJ3nGZvgGesp9lt1sFuIcpBncMxzPSIVMUC/lights/1/state>>>, and body <<<{"on": false}>>>
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,599 [qtp18195028-86] DEBUG spark.Request - matchedPart: :userid = uhWjJQJ3nGZvgGesp9lt1sFuIcpBncMxzPSIVMUC
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,600 [qtp18195028-86] DEBUG spark.Request - matchedPart: :id = 1
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,616 [qtp18195028-86] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue state change requested: uhWjJQJ3nGZvgGesp9lt1sFuIcpBncMxzPSIVMUC from 192.168.1.12 body: {"on": false}
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,641 [qtp18195028-86] DEBUG com.bwssystems.HABridge.BridgeSecurity - validateWhitelistUser: found a user <uhWjJQJ3nGZvgGesp9lt1sFuIcpBncMxzPSIVMUC>
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,647 [qtp18195028-86] DEBUG com.bwssystems.HABridge.hue.HueMulator - Calling on-off as requested.
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,649 [qtp18195028-86] DEBUG com.bwssystems.HABridge.hue.HueMulator - Decode Json for url items: [{"item":"{\"device\":\"53715617\",\"button\":\"AllLightsOff\",\"hub\":\"Harmony Hub\"}","type":"harmonyButton"}]
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,662 [qtp18195028-86] DEBUG com.bwssystems.HABridge.hue.HueMulator - Calling Home device handler for type : harmonyButton
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,676 [qtp18195028-86] DEBUG com.bwssystems.HABridge.plugins.harmony.HarmonyHome - executing HUE api request to change harmonyButton to Harmony: Library Light
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,678 [qtp18195028-86] DEBUG com.bwssystems.HABridge.plugins.harmony.HarmonyHome - pressing button: 53715617 - AllLightsOff with pressTime of: null - iteration: 0 - count: 0
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,679 [qtp18195028-86] DEBUG com.bwssystems.HABridge.plugins.harmony.HarmonyHandler - Harmony api press a button requested for device: 53715617 and a for button: AllLightsOff with pressTime of: null for a hub: Harmony Hub noop mode: false

Request 2:
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,560 [qtp18195028-87] DEBUG com.bwssystems.HABridge.hue.HueMulator - HueMulator PUT called on api/* with request <<</api/4b056b4e02024030b40760eba0099306/lights/1/state>>>, and body <<<{"on":false}>>>
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,614 [qtp18195028-87] DEBUG spark.Request - matchedPart: :userid = 4b056b4e02024030b40760eba0099306
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,671 [qtp18195028-87] DEBUG spark.Request - matchedPart: :id = 1
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,672 [qtp18195028-87] DEBUG com.bwssystems.HABridge.hue.HueMulator - hue state change requested: 4b056b4e02024030b40760eba0099306 from 192.168.1.19 body: {"on":false}
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,673 [qtp18195028-87] DEBUG com.bwssystems.HABridge.BridgeSecurity - validateWhitelistUser: found a user <4b056b4e02024030b40760eba0099306>
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,674 [qtp18195028-87] DEBUG com.bwssystems.HABridge.hue.HueMulator - Calling on-off as requested.
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,675 [qtp18195028-87] DEBUG com.bwssystems.HABridge.hue.HueMulator - Decode Json for url items: [{"item":"{\"device\":\"53715617\",\"button\":\"AllLightsOff\",\"hub\":\"Harmony Hub\"}","type":"harmonyButton"}]
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,682 [qtp18195028-87] DEBUG com.bwssystems.HABridge.hue.HueMulator - Calling Home device handler for type : harmonyButton
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,683 [qtp18195028-87] DEBUG com.bwssystems.HABridge.plugins.harmony.HarmonyHome - executing HUE api request to change harmonyButton to Harmony: Library Light
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,685 [qtp18195028-87] DEBUG com.bwssystems.HABridge.plugins.harmony.HarmonyHome - pressing button: 53715617 - AllLightsOff with pressTime of: null - iteration: 0 - count: 0
Apr  3 19:09:35 chip java[238]: 2018-04-03 19:09:35,707 [qtp18195028-87] DEBUG com.bwssystems.HABridge.plugins.harmony.HarmonyHandler - Harmony api press a button requested for device: 53715617 and a for button: AllLightsOff with pressTime of: null for a hub: Harmony Hub noop mode: false

**Comment by tuicemen** [comment]
I also get two commands coming from Amazon maybe HA-Bridge could have a setting to reject the second call if the same as the first, limiting it to a short time interval.

**Comment by bwssytems** [comment]
@tuicemen Well that is a dangerous solution. 

Also, are there any duplicate entries for the device in the Plus?

**Comment by bwssytems** [comment]
Any update on this?
