### ISSUE TITLE
dim command to execute scripts via Alexa?

### ISSUE THREAD

**Issue by 1punkt0** [bwssytems/ha-bridge#958]
Hello,
the ha-bridge project is great. Thanks for sharing it. 

is it possible to trigger different scripts with the "dim command" via Alexa?
i use an hyperion ambilight on my TV (https://hyperion-project.org/wiki/Main)
with the ha-bridge i can turn on and off the ambilight via different scripts on my raspberry with Alexa.
now i want to set the brightness in percent.

example:
Alexa, set "ambilight" to 10% 
then a script on the raspberry shoud start, wich set the brightness to 10%
 
Alexa, set "ambilight" to 50% 
then a **different** script on the raspberry shoud start, wich set the brightness to 50%

is that possible with the dim function?

Thanks
please excuse my bad English : )

**Comment by bwssytems** [comment]
Yes, you can do this. Put your script into the dim command field and use the type "Execute Command/Script/Program". After the script name, use the intensity variable to pass the value to your script. the percent variable to use is ```${intensity.percent}```. This will pass a value of 0 - 100 to your script based on what the ha-bridge receives.

**Comment by bwssytems** [comment]
Did this solve your issue?

**Comment by 1punkt0** [comment]
Thanks! i will try that, i think that works!

**Comment by amyth1884** [comment]
Could you please share an example. This is what I have [{"item":"sudo /home/pi/irrp.py -p -g22 -f/home/pi/MicroMax ON","type":"cmdDevice"}] I want to use different intentsity levels to trigger different script values

**Comment by amyth1884** [comment]
Where do I need to add ${intensity.percent} to execute a specific script

**Comment by BlueDawnx** [comment]
"/home/pi/ha-bridge/hyperion/hyperion_dim.sh ${intensity.percent}" like that i think. But what does the script looks like? I can't get it to work, could anyone help out?

**Comment by Nero3ooo** [comment]
me too, I wrote python scripts for changing color and turning on and off.
I save the color and the brightness in an extra file to remember color, while I switch between on and off and so on.
but alexa is too intelligent^^ 
When I say: alexa, set "hyperion" to green
${color.rgbx} = 00FF00
When I say: alexa, set "hyperion" to 80%
then ${intensity.percent} = 80, ${color.rgbx} is not given
When I say: alexa, set "hyperion" to red
${color.rgbx} = CC0000 instead of FF0000
so it scales after changing color, but I can't change it direct after setting brightness.

sorry, my english is not as good as it should be.
hope you understand my problem and anyone could help.

ps:
@BlueDawnx there is ${color.rgbx}. It gives the hex code.
in python you can change it to decimal with something like this: tuple(int(sys.argv[1][i:i+2], 16) for i in (0, 2, 4))

to send a json request to hyperion in python you need this:
import requests, json
header = {'Content-Type':'application/json'}
payload = {"command":"color", "color":color_value, "priority":50, "origin":"ha bridge"}
link = "HTTP://your_hyperion_server_ip:your_hyperion_server_port/json-rpc"
r = requests.post(url = link, json = payload, headers = header)

**Comment by Raynman77** [comment]
> Yes, you can do this. Put your script into the dim command field and use the type "Execute Command/Script/Program". After the script name, use the intensity variable to pass the value to your script. the percent variable to use is `${intensity.percent}`. This will pass a value of 0 - 100 to your script based on what the ha-bridge receives.

I'm having trouble with this when trying to run my python script on a raspberry pi. I'm importing python's module 'system' to get the `sysargv[1]` from the target item for executing my script, but it seems like that string argument is not being passed to the python script. When including `${intensity.percent}` at the end of the target item command, exactly what arguments are being passed to the script? I thought it was just the one argument to the call + the script making the `sysargv[1]` the string value of intensity.
