### ISSUE TITLE
Ha-bridge not responding to alexa after a while

### ISSUE THREAD

**Issue by Markuno79** [bwssytems/ha-bridge#959]
hello,

I changed my router to a edgerouter 6 from ebiquiti and because of this my ip range changed and had to reinstall the HA-Bridge on my synology because i was not able to change and save the ip adress for some reason on the running bridge software.
Now at first everything seemed to be running fine really fast responses from devices but after a while when you ask alexa to activate a device she tells me the device is not responding.
when i log into the bridge and switch devices everything works fine.
Then i found out after i log onto the Alexa website everything starts functioning again.
This problem keeps returning and can't seem to find out why this is.
Does anybody have any suggestions for me?

**Comment by bwssytems** [comment]
Make sure your ip address in the bridge control is set to the ip address of the host.

**Comment by Markuno79** [comment]
the ip adress is set to the host but i'm beginning to think the bridge is not the problem because if i switch devices on the bridge manually everything works fine.
i found out that if the connection can't be made to the bridge by alexa after a while and i logon to the router main page it starts working again so not only the alexa website.
It can work fine for a day and then the problem comes back again.

**Comment by Kat-CeDe** [comment]
Hi,
in my case I am switching off an Echo when not used. I also had the response from Alexa that the (HA-bridge) device is not responding. I then started the Alexa app and she showed a server error and said that the Echo is not reachable. Do you switch of Echos or Dots? At the moment I think that I get this error when I switch off an Echo which communicates with Amazon at this time.

Ralf

**Comment by LenPC** [comment]
I am also experiencing this issue where Alexa seems to lose the connection to the HA Bridge (resulting in the "<device> is not responding" message.  It seems to be on the Alexa-side for me because when I examine the HA Bridge logs, I don't see any evidence of Alexa's request's.  I can restore the connection after some combination of 1) having Alexa "discover my devices" and restarting the HA Bridge, but I haven't figured the right sequence to get things to work - I often have to repeat one or both.  I haven't tried logging into the website yet to see if that works.

**Comment by Markuno79** [comment]
i have an echo spot and a dot both have the same issue. 
The problem here is when she tells me the device is not responding i found out when asking again after some minutes it works again.
I changed my network switch and installed the ha-bridge on a raspberry but problem keeps the same.
At home i have 2 diffrent wifi channel names one is the 5ghz and the other  2.4ghz because some devices have problems with the 5ghz.
i recently changed both echo devices from the 5ghz wifi to the 2.4ghz and it looks like  it is working better now but still have to wait a couple of days to be sure.

**Comment by LenPC** [comment]
I am still baffled by this issue.  Alexa goes from being able to control devices to "not responding".  I've tried 1) Rediscovering devices, 2) forgetting and rediscovering devices, 3) resetting the bridge, 4) pinging the echo (they don't respond to pings), 5) logging into the alexa app (mobile and desktop).  Nothing seems to work.  Any advice on what diagnostics I should be looking at to figure out what's happening would be a great help.

**Comment by Markuno79** [comment]
When switching back to ha-bridge on synology i got the same problems i have
to rediscover to let everything work again.
I now have HA bridge running on a raspberry pi on lan cable,switched both
alexa devices on wifi 2.4ghz and switched my wifi signal strengt to medium.
It seems to work now for 95 procent, sometimes it still doesn't respond but
asking again after a while it works.
I don't know if this solves your problem but it seems to work better for me
but still not perfect.

2018-06-02 19:15 GMT+02:00 LenPC <notifications@github.com>:

**Comment by LenPC** [comment]
I ran into the "... not responding" problem again.  Resetting the HA Bridge didn't solve the problem, but I asked Alexa to "drop in on the kitchen" (another dot in the house), and immediately told her to "hang up" and retired the command and Alexa was able to control the device "ok"....at least there might be a way to get things working when it happens.  I'll keep checking on my end.

**Comment by Markuno79** [comment]
it seems like you have same problems i had,i still think it has something to do with wifi or router because for me it always worked on my old asus router without any problems,it started when changing my router and changing to an access point.
I added an diffrent access point to my network, now have 2 to see if it will work better.

**Comment by mikelhall** [comment]
I have this same issue. If you wait after the first request, the connection will re-establish and Alexa will perform the action. One way around this I found, was to use IFTTT. The phrase would changed to "Alexa, trigger diningroom light on" instead of "Alexa, turn diningroom light on". I found that IFTTT works with few response problems. Using IFTTT first will most often times get Alexa performing your normal response. If you have the Alexa app on your phone, you can open one of your devices and see that a "no response" will come up, then eventually disappear. At that point, your device is ready.

**Comment by dghh** [comment]
I have the same problem since the last two or three releases. I think it is because if anything happens, like router was down or bad connection or harmony is down or something like this, habridge does not connect again automatically. Everything is fine after restarting habridge again. Is it not possible to have in the habridge a kind of keep a live or heartbeat which checks in short times whether all connected devices like harmony are still connected? I myself cannot find a way in habridge to check this. Error logs are not easy accessible. Automatic reconnection would help a lot in this cases.

**Comment by jonosl** [comment]
I have the same issue, sometimes if you ask 3-4 times it might work but ultimately a ha-bridge reboot fixes it. I have static ip's for habridge and vera and if i manually test the z wave device it works fine using vera Luup. I'm thinking of setting up a auto reboot every night at 3am

kind regards,

Jonathan

**Comment by LenPC** [comment]
I seem to have found the solution to the problem I was seeing with HABridge running on Windows 10 Professional.  The problem hasn't recurred since I changed the power management options for the ethernet driver that HABridge was using.  The instructions I used can be found here: https://answers.microsoft.com/en-us/windows/forum/windows_10-networking-winpc/windows-10-internet-connection-keeps-disconnecting/fc5caf83-bee6-4cbe-9490-86c7db17ea12 
I read on other posts that the defaults for the power mgmt. settings were recently changed with a Windows update which would explain why this happened only recently.

**Comment by jonosl** [comment]
I run a Rpi3 stock following the guide, i wonder if its ever since i upgraded from v4 to v5 of habridge the issues started happening

**Comment by mikelhall** [comment]
Making the change to the ethernet power to not effected by the computer fixed my issue with no response at first with Alexa. Thanks guys.

**Comment by dghh** [comment]
I have still the same problem that habridge does not reconnect to Alexa after a power failure or router was rebootet. As i have running habridge on a raspberry, with lan and not wlan, there are no power management options and the lan on the raspberry is pretty stable. Is habridge still maintained? It is a fantastic and very helpful project and it would be very bad in case.

**Comment by bwssytems** [comment]
@Markuno79 @dghh  So, with your routers are you all setting the ip address for the ha-bridge to a static IP?

**Comment by LenPC** [comment]
In my case, I am using static dhcp (I have the router set to always give the same IP address based on the mac address of the PC’s network card)

**Comment by dghh** [comment]
Yes, every IP is static in my network

**Comment by bwssytems** [comment]
So, I will need to see logs with trace upnp turned on and the ips of your echos....

**Comment by bwssytems** [comment]
Any update on this?
