### ISSUE TITLE
Windows install - won't create /data or habridge.config files

### ISSUE THREAD

**Issue by HouliNZ** [bwssytems/ha-bridge#971]
Hi,

Great software.  I got it working well with X10 commander (for my X10 lights) however it won't save my settings/devices because Ha Bridge) on Windows doesnt appear to create the device and config files.  the install didn't create blank ones either - so I assume they are created on first run.  Bridge control has paths (unix format) that I can't update because they don't save.

Ideas?  what am I missing?

**Comment by bwssytems** [comment]
How are you starting it on windows?

**Comment by tuicemen** [comment]
where is your HA-Bridge jar file located? (full path)

**Comment by HouliNZ** [comment]
Yes it is certainly starting on Windows.  He full path to the JAR file is "C:\Program Files (x86)\HA Bridge" and the filename is "ha-bridge-5.2.1.jar"

**Comment by tuicemen** [comment]
Windows 10 64 bit has extra security (Read/write permissions) implemented for programs running from Program Files (x86). in fact Microsoft is starting to implement that for all 64 bit versions and I suspect 32 bit versions may follow.
This stops programs from editing (creating) files in Program files (x86)
The fix for this is to either run HA-Bridge as administrator or move it out of that folder, logging on Windows as an administrator won't help.

**Comment by bwssytems** [comment]
Included in the community information https://github.com/bwssytems/ha-bridge/wiki/Informational-Items-Collected-from-the-Community#q-windows-install--wont-create-data-or-habridgeconfig-files
