### ISSUE TITLE
Contact and Motion Sensor support

### ISSUE THREAD

**Issue by BuxtonCalvin** [bwssytems/ha-bridge#993]
Are there any plans to support the new Alexa sensor API?  https://developer.amazon.com/blogs/alexa/post/bda9d70c-2f0d-454d-9939-2eb82868cf35/announcing-contact-and-motion-sensor-apis-and-integration-into-alexa-routines-adding-new-home-automation-features-for-customers-and-new-opportunities-for-smart-home-developers

I use the ha-bridge with my vera and being able to ask Alexa about sensor status (through the Vera) would be awesome.

**Comment by BuxtonCalvin** [comment]
I didn't realize that.  Thx for the answer.  I think it would be helpful to other readers if you place that info at the top of the readme with some deeper background on how alexa works with Philips Hue as opposed to all the other skills.  It now makes sense to me why the bridge does what it does.

**Comment by rubenkr** [comment]
Hi there,

I had the same idea, BUT with the hue system. Philips Hue Motion Sensor should control my TP-Link HS110 outlet. Is it possible that I can emulate my HS110 as hue device - in that way the Philips Hue app recognizes it as a Hue Device I can smoothly control via the motion sensor? Any help is much appreciated !! Otherwise are there any other motion sensor ideas to integrate with habridge? Thank you all.
